cyverse-de/ui

de-lib/src/main/java/org/iplantc/de/analysis/client/AnalysesView.java
de-lib/src/main/java/org/iplantc/de/analysis/client/AnalysisToolBarView.java
de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/AnalysesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesToolBarImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesViewImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/widget/AnalysisSearchField.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/dialogs/ManageMetadataDialog.java

Core-8168 disable save button when viewing metadata on read-only resources
Core-8176 fix refresh button in analyses window when using search filter. 
Apologies opening a single PR for 2 bugs. Will get right the next time :)

Core-8176 and Core-8168 bug fixes

---

de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/toolbar/ToolbarViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/dialogs/CreateFolderDialog.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/toolbar/DiskResourceViewToolbarImpl.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/toolbar/ToolbarViewPresenterImplTest.java

CORE-8323 fix NPE when  'New Folder' is clicked without selecting

---

de-webapp/src/main/java/org/iplantc/de/server/websocket/amqp/AMQPConnectionManager.java

Add AMQP vhost cfg property to AMQP connection

---

de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/metadata/MetadataDisplayStrings.properties

Merge directly to origin/master since this is just a property file change.

core-8338 fix the anchor for additional metadata info link

---

de-lib/src/main/java/org/iplantc/de/apps/client/AppDetailsView.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/details/AppDetailsViewImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/details/AppDetailsViewImpl.ui.xml
de-lib/src/main/java/org/iplantc/de/apps/client/views/details/dialogs/AppDetailsDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/details/AppDetailsDefaultAppearance.java

- Add last completed date
- Add total analyses completed
to App details window.

CORE-8423 add stats to details dialog.

---

de-lib/src/main/java/org/iplantc/de/client/models/UserSettings.java
de-lib/src/main/java/org/iplantc/de/client/models/userSettings/UserSetting.java
de-lib/src/main/java/org/iplantc/de/client/models/userSettings/UserSettingAutoBeanFactory.java
de-lib/src/main/java/org/iplantc/de/client/services/UserSessionServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/UserSessionServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/InitializationCallbacks.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/RuntimeCallbacks.java

This PR helps the UI to be more consistent by moving away from using JSONObjects and Splittables to AutoBeans for user settings.  The singleton `UserSettings` is still maintained to facilitate setting default values.

CORE-8432 Refactor UserSettings to AutoBean

---

.gitignore
de-lib/src/main/java/org/iplantc/de/apps/client/events/EditAppEvent.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/submit/SubmitAppForPublicUseViewImpl.java
de-lib/src/main/java/org/iplantc/de/apps/widgets/client/presenter/AppLaunchPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/client/models/apps/PublishAppRequest.java
de-lib/src/main/java/org/iplantc/de/client/models/apps/integration/JobExecution.java
de-lib/src/main/java/org/iplantc/de/client/models/pipelines/PipelineTask.java
de-lib/src/main/java/org/iplantc/de/client/models/pipelines/ServicePipelineStep.java
de-lib/src/main/java/org/iplantc/de/client/services/AppTemplateServices.java
de-lib/src/main/java/org/iplantc/de/client/services/AppUserServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/AppTemplateServicesImpl.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/AppUserServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/commons/client/views/window/configs/ConfigFactory.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterWindowEventHandler.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/windows/AppEditorWindow.java
de-lib/src/main/java/org/iplantc/de/pipelineBuilder/client/builder/PipelineCreator.java
de-lib/src/main/java/org/iplantc/de/pipelineBuilder/client/dnd/DragCreator.java
de-lib/src/main/java/org/iplantc/de/pipelineBuilder/client/json/App.java
de-lib/src/main/java/org/iplantc/de/pipelines/client/util/PipelineAutoBeanUtil.java

This is a fairly significant change, and I wouldn't be surprised if there were issues. A thorough review would be appreciated.

Update the UI to include the system ID in several service endpoint requests.

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/views/MetadataDialog.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/GridView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/DiskResourceMetadataViewImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/dialogs/ManageMetadataDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/GridViewDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/GridViewDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/presenter/GridViewPresenterDefaultAppearance.java

CORE-8424 Remove text field validation. Instead add validation when 

---

de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/AnalysesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/parameters/AnalysisParametersPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/proxy/AnalysisRpcProxy.java
de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/sharing/AnalysisSharingPresenter.java
de-lib/src/main/java/org/iplantc/de/client/services/AnalysisServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/AnalysisServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/shared/AnalysisCallback.java
de-lib/src/test/java/org/iplantc/de/analysis/client/presenter/AnalysesPresenterImplTest.java

This PR builds on top of PR #49 but with changes for the Analysis window.

CORE-8479 UI Resiliency - Analysis Window

---

de-lib/src/main/java/org/iplantc/de/client/services/MessageServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/SystemMessageServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/callbacks/NotificationCallbackWrapper.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/MessageServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/SystemMessageServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/widgets/UnseenNotificationsView.java
de-lib/src/main/java/org/iplantc/de/notifications/client/presenter/NotificationPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/shared/NotificationCallback.java
de-lib/src/main/java/org/iplantc/de/systemMessages/client/presenter/MessagesPresenter.java
de-lib/src/main/java/org/iplantc/de/systemMessages/client/presenter/NewMessagePresenter.java
de-lib/src/test/java/org/iplantc/de/desktop/client/presenter/DesktopNotifications_PresenterTest.java
de-lib/src/test/java/org/iplantc/de/desktop/client/presenter/GetInitialNotificationCallbackWrapperTest.java
de-lib/src/test/java/org/iplantc/de/desktop/client/presenter/GetRecentNotificationCallbackWrapperTest.java
de-lib/src/test/java/org/iplantc/de/notifications/client/presenter/NotificationPresenterImplTest.java

This PR builds on top of PR #49 but with changes for the Notification window.

CORE-8481 UI Resiliency - Notification Window

---

de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesToolBarImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/toolBar/AppsViewToolbarImpl.java
de-lib/src/main/java/org/iplantc/de/client/models/analysis/Analysis.java
de-lib/src/test/java/org/iplantc/de/analysis/client/views/AnalysesToolBarImplTest.java

Also fixed a typo: sharable => shareable.

CORE-8540 Enable analysis sharing for any status.

---

de-lib/src/main/java/org/iplantc/de/commons/client/views/window/configs/ConfigFactory.java

Window tag was to set to current day. So opening several new files was not possible in a single session. I have updated it use full date/time.

CORE-8568 allow users to open / edit multiple new files

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/views/UpdatePermanentIdRequestDialog.java
de-lib/src/main/java/org/iplantc/de/client/models/identifiers/PermanentIdRequestDetails.java
de-lib/src/main/java/org/iplantc/de/client/models/identifiers/PermanentIdRequestStatus.java

Also, Fix UI NPE when Updating a DOI request.

CORE-8569 add Rejected and Test Status. 

---

de-lib/src/main/java/org/iplantc/de/analysis/client/AnalysesView.java
de-lib/src/main/java/org/iplantc/de/analysis/client/AnalysisParametersView.java
de-lib/src/main/java/org/iplantc/de/analysis/client/AnalysisToolBarView.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/AnalysisCommentUpdate.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/AnalysisFilterChanged.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/selection/AnalysisJobInfoSelected.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/selection/CancelAnalysisSelected.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/selection/DeleteAnalysisSelected.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/selection/GoToAnalysisFolderSelected.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/selection/RefreshAnalysesSelected.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/selection/RelaunchAnalysisSelected.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/selection/RenameAnalysisSelected.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/selection/ShareAnalysisSelected.java
de-lib/src/main/java/org/iplantc/de/analysis/client/gin/factory/AnalysesViewFactory.java
de-lib/src/main/java/org/iplantc/de/analysis/client/gin/factory/AnalysisToolBarFactory.java
de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/AnalysesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/parameters/AnalysisParametersPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesToolBarImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesViewImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/dialogs/AnalysisCommentsDialog.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/dialogs/AnalysisParametersDialog.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/dialogs/AnalysisStepsInfoDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/AnalysesMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/AnalysesMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/AnalysesViewDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/AnalysisParametersViewDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/presenter/AnalysesPresenterDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/analysis/client/presenter/AnalysesPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/analysis/client/views/AnalysesToolBarImplTest.java

These are a bunch of really small, repetitive changes - mostly switching to events.  I don't feel it's necessary for a deep review on these changes, but figured I'd put it up in a PR just in case I missed something obvious.

CORE-8602 Part 1 - Refactor the Analysis module for code consistency

---

de-webapp/src/main/java/org/iplantc/de/admin/belphegor.gwt.xml
de-webapp/src/main/java/org/iplantc/de/discoveryenvironment.gwt.xml
de-webapp/src/main/java/org/iplantc/de/server/rpc/DeGwtRemoteLoggingServiceImpl.java
de-webapp/src/main/java/org/iplantc/de/server/rpc/GwtRpcController.java

This branch is based off of the GWT 2.8 branch, so only the last commit is relevant.
The one thing I'm not sure of is how to get the module name (DE or Belphy) from the server side code in a clean way. Right now I'm doing a regex and I get the feeling there's an easier way but I don't know the server side stuff well enough.

CORE-7582 GWT Stack Trace Deobfuscation

---

de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/AnalysesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/parameters/AnalysisParametersPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/sharing/AnalysisSharingPresenter.java
de-lib/src/main/java/org/iplantc/de/client/models/diskResources/File.java
de-lib/src/main/java/org/iplantc/de/client/models/notifications/Notification.java
de-lib/src/main/java/org/iplantc/de/client/models/notifications/payload/PayloadData.java
de-lib/src/main/java/org/iplantc/de/client/services/UserSessionServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/UserSessionServiceFacadeImpl.java

These are refactoring changes that probably merit a second pair of eyes.

CORE-8602 Part 2 - Refactor the Analysis module for code consistency

---

de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/RuntimeCallbacks.java

The logging wasn't as bad as I initially thought - mostly had to switch some client side logging to server side.

CORE-8625 Update UI logging during logout

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/gin/BelphegorAppsGinModule.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/presenter/PermanentIdRequestPresenter.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/views/MetadataDialog.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/views/PermanentIdRequestView.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/views/PermanentIdRequestViewImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/GridView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/MetadataView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/gin/DiskResourceGinModule.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/MetadataPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/DiskResourceMetadataEditorPanel.ui.xml
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/DiskResourceMetadataViewImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/MetadataTemplateView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/dialogs/ManageMetadataDialog.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/dialogs/MetadataTemplateViewDialog.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/dialogs/MetadataTermGuideDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/presenter/GridViewPresenterDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/metadata/MetadataDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/metadata/MetadataDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/metadata/MetadataPresenterDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/metadata/MetadataViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/metadata/MetadataPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/views/metadata/MetadataTemplateViewTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/views/metadata/dialogs/MetadataTemplateViewDialogTest.java

- Change Accordion layout to Tabs
- Split view and Dialog
- DI and code splits
- Fix bugs

Core 8591 Allow repeating template fields-Refactor code based on PR Comments 

---

de-lib/src/main/java/org/iplantc/de/pipelines/client/presenter/PipelineViewPresenter.java
de-lib/src/main/java/org/iplantc/de/pipelines/client/views/PipelineAppOrderView.ui.xml
de-lib/src/main/java/org/iplantc/de/pipelines/client/views/PipelineAppOrderViewImpl.java

- CORE-4419 fix button state.
- CORE-6741 fix step number when removing an app.

Pipeline fix

---

de-lib/src/main/java/org/iplantc/de/diskResource/client/ToolbarView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/toolbar/DiskResourceViewToolbarImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/toolbar/dialogs/DOIAgreementDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/toolbar/ToolbarDisplayMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/toolbar/ToolbarDisplayMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/toolbar/ToolbarViewDefaultAppearance.java

A check box for user to acknowledge that they have read the agreement.

DC-92 Add DC user agreement to DOI Request dialog.

---

de-lib/src/main/java/org/iplantc/de/client/models/groups/Group.java
de-lib/src/main/java/org/iplantc/de/client/models/groups/GroupList.java
de-lib/src/main/java/org/iplantc/de/client/services/CollaboratorsServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/GroupServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/GroupServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/GroupView.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/ManageCollaboratorsView.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/events/DeleteGroupSelected.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/models/GroupProperties.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenter.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/GroupDetailsView.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/GroupViewImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/ManageCollaboratorsViewImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/cells/GroupNameCell.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/dialogs/GroupDetailsDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/GroupDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/GroupDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/GroupViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenterTest.java

These are the changes for deleting a Collaborator List (group).

CORE-8752 Allow users to delete Collaborator Lists

---

de-lib/src/main/java/org/iplantc/de/client/services/GroupServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/GroupServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/ManageCollaboratorsView.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenter.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/GroupViewImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/ManageCollaboratorsViewImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/cells/GroupNameCellDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenterTest.java
de.properties.tmpl

These are minor fixes after some testing with the new terrain endpoints for Collaborator Lists.

Minor fixes for Collaborator Lists

---

de-lib/src/main/java/org/iplantc/de/client/services/GroupServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/GroupServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/GroupDetailsView.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/GroupView.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/events/DeleteMembersSelected.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/presenter/GroupDetailsPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/GroupDetailsViewImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/GroupDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/GroupDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/GroupViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/collaborators/client/presenter/GroupDetailsPresenterImplTest.java

NOTE: This is currently another PR on top of branches on top of branches.  The only new commits start from `CORE-8793 Add service call for deleting a member from a Group`. You can use [this link](https://github.com/cyverse-de/ui/pull/125/files/27fd72f808cc716554d2f1108db634d23c13bf05..07a25e76ec7e51b09656cf65f7d1065477a96ae9) to view just those commits.

CORE-8793 Allow users to delete members from a Group

---

de-lib/src/main/java/org/iplantc/de/analysis/client/gin/AnalysisGinModule.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesViewImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysisColumnModel.java

This took me longer to find than I'd have liked, but basically we were injecting a ColumnModel that had a separate CheckBoxSelectionModel than the one created and used in the view.

CORE-8844 Allow users to de-select analyses in the analysis window

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolAdmin/service/impl/ToolAdminServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolAdmin/view/ToolAdminViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolRequest/presenter/ToolRequestPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolRequest/view/ToolRequestViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolRequest/view/UpdateToolRequestDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/tools/ManageToolsViewDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/tools/NewToolRequestFormViewDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/tools/ToolMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/tools/ToolMessages.properties
de-lib/src/main/java/org/iplantc/de/tools/client/presenter/ToolSharingPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/dialogs/EditToolDialog.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/dialogs/NewToolRequestDialog.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/dialogs/ToolSharingDialog.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/manage/EditToolViewImpl.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/manage/ManageToolsView.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/manage/ManageToolsViewImpl.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/manage/ManageToolsViewToolbarImpl.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/manage/ToolSharingViewImpl.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/requests/NewToolRequestFormView.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/requests/NewToolRequestFormViewImpl.java

- Contains a bug fix. I was using a non-admin end-point in belphegor. 
- Java 8 refactors.
- Introduced appearances in few places i missed.

Core 8416 ref

---

de-lib/src/main/java/org/iplantc/de/client/util/DiskResourceUtil.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/grid/GridViewDnDHandler.java

I couldn't find what specific action caused the index out of bounds error, but I did find some NPEs and figured we could patch up the index error.  Let me know if we'd feel more comfortable trying to pin down what causes the error instead.

Patch up NPE and index out of bounds error during DND

---

de-lib/src/main/java/org/iplantc/de/admin/apps/client/AdminAppStatsGridViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/apps/client/views/grid/cells/AvgAppRatingCell.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/list/AppsTileViewImpl.java
de-lib/src/main/java/org/iplantc/de/client/models/apps/AppFeedback.java
de-lib/src/main/java/org/iplantc/de/client/models/apps/AppRatingComparator.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/AppUserServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppCardCellDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppRatingCellDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppTileCellDefaultAppearance.java

Fix the following warnings:
`11:05:12 Compiling module org.iplantc.de.discoveryenvironment
11:08:03    Computing all possible rebind results for 'org.iplantc.de.apps.client.models.AppProperties'
11:08:03       Rebinding org.iplantc.de.apps.client.models.AppProperties
11:08:03          Invoking generator com.sencha.gxt.data.rebind.PropertyAccessGenerator
11:08:03             Building method: public abstract com.sencha.gxt.core.client.ValueProvider<org.iplantc.de.client.models.apps.App, java.lang.Double> rating()
11:08:03                Running class com.sencha.gxt.data.rebind.ValueProviderCreator
11:08:03                   [WARN] Method getAverage could not be found
11:08:13    Computing all possible rebind results for 'org.iplantc.de.theme.base.client.apps.cells.AppTileCellDefaultAppearanc …

Fix warnings that occur during DE build

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolAdmin/view/dialogs/ToolAdminDetailsDialog.java
de-lib/src/main/java/org/iplantc/de/client/models/tool/ToolAutoBeanFactory.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/ToolServicesImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/tools/EditToolViewDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/tools/ToolMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/tools/ToolMessages.properties
de-lib/src/main/java/org/iplantc/de/tools/client/presenter/ManageToolsViewPresenter.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/manage/EditToolView.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/manage/EditToolView.ui.xml
de-lib/src/main/java/org/iplantc/de/tools/client/views/manage/EditToolViewImpl.java

- Also refactor code to use Editor framework.

Core 8914 Allow users to set entrypoint for their private tools

---

de-webapp/src/main/java/org/iplantc/de/Application.java
de-webapp/src/main/java/org/iplantc/de/server/HttpSessionConfig.java
de.properties.tmpl
iplant/webapps.gradle

- Configure Spring to use Redis for session management
- This code requires Ansible changes

CORE-8923 Implement session management for UI

---

de-lib/src/main/java/org/iplantc/de/collaborators/client/ManageCollaboratorsView.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/gin/ManageCollaboratorsViewFactory.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenter.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/CollaboratorDNDHandler.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/ManageCollaboratorsViewImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/CollaboratorsDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/CollaboratorsDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/ManageCollaboratorsViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenterTest.java

Now you can DND collaborators (users and lists) to another list to add them to that list.

CORE-8911 Add DND ability to add collaborators to lists

---

de-lib/src/main/java/org/iplantc/de/client/models/collaborators/Subject.java
de-lib/src/main/java/org/iplantc/de/client/models/groups/PrivilegeType.java
de-lib/src/main/java/org/iplantc/de/client/services/GroupServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/GroupServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/presenter/GroupDetailsPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenter.java
de-lib/src/main/java/org/iplantc/de/shared/DEProperties.java
de-lib/src/main/java/org/iplantc/de/teams/client/EditTeamView.java
de-lib/src/main/java/org/iplantc/de/teams/client/TeamsView.java
de-lib/src/main/java/org/iplantc/de/teams/client/events/EditTeamSelected.java
de-lib/src/main/java/org/iplantc/de/teams/client/presenter/EditTeamPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/teams/client/presenter/TeamsPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/teams/client/views/EditTeamViewImpl.java
de-lib/src/main/java/org/iplantc/de/teams/client/views/TeamsViewImpl.java
de-lib/src/main/java/org/iplantc/de/teams/client/views/TeamsViewImpl.ui.xml
de-lib/src/main/java/org/iplantc/de/theme/base/client/teams/TeamsViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/collaborators/client/presenter/GroupDetailsPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenterTest.java
de-lib/src/test/java/org/iplantc/de/teams/client/presenter/EditTeamPresenterImplTest.java
de.properties.tmpl

A lot of the extra changes in `EditTeamPresenterImpl` are due to wanting to organize all the methods in there a little better, so sorry for the clutter.

CORE-8903 Editing teams

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolAdmin/ToolAdminView.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolAdmin/view/ToolAdminDetailsView.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolAdmin/view/ToolAdminDetailsView.ui.xml
de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/toolAdmin/ToolAdminDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/toolAdmin/ToolAdminDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/toolAdmin/ToolAdminViewDefaultAppearance.java

* Also fixed missed validation checks.

core-8963 Add ability to remove time limits to tool.

---

de-lib/src/main/java/org/iplantc/de/analysis/client/views/cells/AnalysisUserSupportCell.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/AppTemplateServicesImpl.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/DiskResourceServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/commons/client/views/dialogs/SimpleFileUploadDialog.java
de-lib/src/main/java/org/iplantc/de/commons/ui-commons.gwt.xml
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopWindowManager.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/InitializationCallbacks.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/DesktopViewImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/windows/DEAppsWindow.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/windows/DeDiskResourceWindow.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/windows/IPlantWindowInterface.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/windows/IplantWindowBase.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/windows/MyAnalysesWindow.java
de-lib/src/main/java/org/iplantc/de/intercom/Intercom.gwt.xml
de-lib/src/main/java/org/iplantc/de/intercom/client/IntercomFacade.java
de-lib/src/main/java/org/iplantc/de/intercom/client/TrackingEventType.java
de-lib/src/main/java/org/iplantc/de/notifications/client/utils/NotifyInfo.java
de-lib/src/main/java/org/iplantc/de/shared/DEProperties.java
de-webapp/src/main/java/org/iplantc/de/server/controllers/DeController.java
de-webapp/src/main/webapp/WEB-INF/jsp/de.jsp
de.properties.tmpl

- Inject Intercom javascript only if it is enabled through our properties
- Create a separate module to interact with Intercom API
- Track user activities using Intercom API (if enabled)
- This changes requires Ansible changes to configure and enable Intercom

Core 8971 Integrate Intercom API

---

de-lib/src/main/java/org/iplantc/de/collaborators/client/util/UserSearchField.java
de-lib/src/test/java/org/iplantc/de/collaborators/client/util/SubjectSortComparatorTest.java

Fixes NPE for subject entities that don't have a first or last name.
Now comparing group names, then last name, then first name, then name, then id

CORE-8990 Refactor Subject name comparator to fix NPE

---

de-lib/src/main/java/org/iplantc/de/client/models/groups/Group.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenter.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/cells/SubjectNameCell.java
de-lib/src/main/java/org/iplantc/de/notifications/client/presenter/NotificationPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/notifications/client/views/dialogs/ApproveJoinRequestDialog.java
de-lib/src/main/java/org/iplantc/de/notifications/client/views/dialogs/DenyJoinRequestDialog.java
de-lib/src/main/java/org/iplantc/de/teams/client/EditTeamView.java
de-lib/src/main/java/org/iplantc/de/teams/client/TeamsView.java
de-lib/src/main/java/org/iplantc/de/teams/client/events/PrivilegeAndMembershipLoaded.java
de-lib/src/main/java/org/iplantc/de/teams/client/models/GroupProperties.java
de-lib/src/main/java/org/iplantc/de/teams/client/models/PrivilegeProperties.java
de-lib/src/main/java/org/iplantc/de/teams/client/presenter/EditTeamPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/teams/client/presenter/TeamsPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/teams/client/views/EditTeamViewImpl.java
de-lib/src/main/java/org/iplantc/de/teams/client/views/TeamsViewImpl.java
de-lib/src/main/java/org/iplantc/de/teams/client/views/dialogs/DeleteTeamDialog.java
de-lib/src/main/java/org/iplantc/de/teams/client/views/dialogs/EditTeamDialog.java
de-lib/src/main/java/org/iplantc/de/teams/client/views/dialogs/JoinTeamDialog.java
de-lib/src/main/java/org/iplantc/de/teams/client/views/dialogs/LeaveTeamDialog.java
de-lib/src/main/java/org/iplantc/de/teams/client/views/dialogs/SaveTeamProgressDialog.java
de-lib/src/main/java/org/iplantc/de/teams/shared/Teams.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/teams/TeamsDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/teams/TeamsDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/teams/TeamsViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenterTest.java
de-lib/src/test/java/org/iplantc/de/teams/client/presenter/EditTeamPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/teams/client/presenter/TeamsPresenterImplTest.java

NOTE: This is a branch on top of branches.  The first commit for just this PR starts at `CORE-8900 Remove OK button from EditTeamDialog if not admin`
This is just a bunch of little fixes... fixing static IDs, adding help text, making clearer messages, adding team creator names to the team listings, etc.

Misc. Team Fixes

---

de-lib/src/main/java/org/iplantc/de/analysis/client/AnalysesView.java
de-lib/src/main/java/org/iplantc/de/analysis/client/AnalysisToolBarView.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/AnalysisCommentUpdate.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/selection/RenameAnalysisSelected.java
de-lib/src/main/java/org/iplantc/de/analysis/client/events/selection/ViewAnalysisParamsSelected.java
de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/AnalysesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesToolBarImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesViewImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysisColumnModel.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/cells/AnalysisAppNameCell.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/cells/AnalysisDotMenuCell.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/cells/AnalysisNameCell.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/cells/AnalysisUserSupportCell.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/widget/AnalysisDotMenu.java
de-lib/src/main/java/org/iplantc/de/analysis/shared/AnalysisModule.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/Analyses.gwt.xml
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/AnalysesViewDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/cells/AnalysisAppNameCellDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/cells/AnalysisDotMenuDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/cells/AnalysisNameCellDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/cells/AnalysisUserSupportCellDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/presenter/AnalysesPresenterDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/analysis/client/presenter/AnalysesPresenterImplTest.java

NOTE: This is a branch on top of a branch.  The commits for this PR start at `CORE-8997 Add dot menu to Analysis window`

CORE-8997 Add dot menu to Analysis window

---

de-lib/src/main/java/org/iplantc/de/client/models/notifications/NotificationCategory.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/GridView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/grid/proxy/FolderContentsRpcProxyImpl.java
de-lib/src/main/java/org/iplantc/de/notifications/client/presenter/NotificationPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/notifications/client/utils/NotificationUtil.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/GridViewDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/GridViewDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/presenter/GridViewPresenterDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/grid/proxy/FolderContentsRpcProxyTest.java

Mostly some notification fixes, but also adding an error message in the Data window if the listing fails (like we've been seeing in the dev environments, but currently without any indication to the user that the listing failed)

MISC Notification fixes

---

de-lib/src/main/java/org/iplantc/de/diskResource/client/views/grid/cells/DiskResourceDotMenuCell.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/widgets/DiskResourceDotMenu.java
de-lib/src/main/java/org/iplantc/de/teams/client/presenter/EditTeamPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/cells/DiskResourceDotMenuDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/cells/DiskResourceDotMenuDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/cells/DiskResourceDotMenuDisplayStrings.properties

* Added some missing loading masks for teams
* Fixed the text for data links in the Data window dot menu
* Also disabled the data link button in the Data window dot menu if the user has a file selected that they do not have own permissions on

Misc fixes

---

de-lib/src/main/java/org/iplantc/de/collaborators/client/util/UserSearchField.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppSearchHighlightAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppSearchHighlightDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppIntegratorCellDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppNameCellDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/details/AppDetailsDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/util/UserSearchFieldDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/util/UserSearchFieldDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/util/UserSearchFieldDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/util/UserSearchResult.html
de-lib/src/test/java/org/iplantc/de/theme/base/client/collaborators/util/MaskUtilTest.java

CORE-8917 Enable subject search highlighting on searched fields

---

de-webapp/src/main/webapp/WEB-INF/jsp/de.jsp

I was looking at this documentation:
https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/customize-the-intercom-messenger-technical
Seems to be working
compared to de-2 right now

Potentially fix Intercom widget position

---

de-lib/src/main/java/org/iplantc/de/client/services/DiskResourceServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/DiskResourceServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/util/CollaboratorsUtil.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/DiskResourcePresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/details/DetailsViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/genome/GenomeSearchPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/grid/GridViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/MetadataPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/sharing/DataSharingPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/toolbar/ToolbarViewPresenterImpl.java
de-lib/src/test/java/org/iplantc/de/client/services/impl/DiskResourceServiceFacadeImplTest.java
de-lib/src/test/java/org/iplantc/de/collaborators/client/util/CollaboratorsUtilTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/DiskResourcePresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/details/DetailsViewPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/genome/GenomeSearchPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/genome/GenomeSearchRpcProxyTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/grid/GridViewPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/metadata/MetadataPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/sharing/DataSharingPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/toolbar/ToolbarViewPresenterImplTest.java

Some small refactors sprinkled in, but mostly for easing testing.

CORE-8470 and CORE-8473 Add tests for the Collaborators and DiskResources modules

---

de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesToolBarImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/toolBar/AppsViewToolbarImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/toolbar/DiskResourceViewToolbarImpl.java

Very small change and I haven't seen any side effects when I was testing.

CORE-9090 Always show the search boxes in Data/Analysis/App windows

---

de-lib/src/main/java/org/iplantc/de/apps/client/views/details/AppDetailsViewImpl.java
de-lib/src/main/java/org/iplantc/de/apps/shared/AppsModule.java
de-lib/src/main/java/org/iplantc/de/commons/client/views/dialogs/ClipboardCopyEnabledDialog.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/DataLinkView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/GridView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/events/selection/ShowDataLinkSelected.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/gin/DiskResourceGinModule.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/gin/factory/DataLinkDialogFactory.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/gin/factory/ShareResourcesLinkDialogFactory.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/dataLink/DataLinkPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/grid/GridViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/dataLink/DataLinkViewImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/dialogs/DataLinkDialog.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/sharing/dialogs/ShareResourceLinkDialog.java
de-lib/src/main/java/org/iplantc/de/fileViewers/FileViewers.gwt.xml
de-lib/src/main/java/org/iplantc/de/fileViewers/client/callbacks/ShareAnonymousCallback.java
de-lib/src/main/java/org/iplantc/de/fileViewers/share/FileViewerModule.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/commons/views/dialogs/ClipboardCopyEnabledDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/dataLink/DataLinkViewDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/presenter/GridViewPresenterDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/fileViewers/FileViewerStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/fileViewers/callbacks/ShareAnonymousCallbackDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/dataLink/DataLinkPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/grid/GridViewPresenterImplTest.java

core-9110 Allow users to copy multiple urls. Refactor code to use 

---

de-webapp/src/main/resources/landing-page-template.html

CORE-9203 Update year and remove Ask link on landing page

---

de-lib/src/main/java/org/iplantc/de/analysis/client/AnalysesView.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesViewImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/AnalysesViewDefaultAppearance.java

Same fix as [CORE-9062](https://pods.iplantcollaborative.org/jira/browse/CORE-9062)

CORE-9222 Increase row height to fix analysis window scroll issue

---

react-components/package-lock.json
react-components/package.json
react-components/src/__tests__/apps.js
react-components/src/__tests__/data.js
react-components/src/apps/admin/AppStats.js
react-components/src/apps/details/ToolDetails.js
react-components/src/apps/style.js
react-components/src/data/details/BasicDetails.js
react-components/src/data/details/InfoTypeSelectionList.js
react-components/src/data/details/Tag.js
react-components/src/data/details/TagPanel.js
react-components/src/data/style.js
react-components/src/util/hyperlink/DEHyperLink.js
react-components/src/util/hyperlink/style.js

- Note: I see some warning in storybook after migrating to JSS but I am not sure how to fix it yet. 
`data/BasicDetails/with test diskresource details error: ["Warning: Material-UI: the key `loadingStyle` provided to the classes property is not implemented in _class.
You can only override one of the following: "]
0: "Warning: Material-UI: the key `loadingStyle` provided to the classes property is not implemented in _class.
You can only override one of the following: `

Migrate from aphrodite to react-jss. Update MUI, react and react-dom versions.

---

react-components/src/apps/admin/AppStats.js
react-components/src/apps/messages.js
react-components/src/apps/style.js
react-components/stories/apps/admin/AppStats.stories.js

This PR will restore App Stats table sorting for the new React/material-ui components.
These changes are largely based on https://material-ui.com/demos/tables/#sorting-amp-selecting

CORE-8430 Restore App Stats table sorting.

---

de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/AnalysesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesToolBarImpl.java

The DE filter was showing all results
OSG filter didn't show any results
All filter didn't show any results if you had switched to a different filter and then switched back to All

CORE-9247 Fix DE, All, and OSG Analysis Type filters

---

de-lib/src/main/java/org/iplantc/de/client/models/viewer/InfoType.java
de-lib/src/main/java/org/iplantc/de/client/util/DiskResourceUtil.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/callbacks/GenomeBrowserUtil.java

Straightforward, I think, but I'd appreciate another set of eyes. Haven't yet shipped this into info-typer or data-info, but it's in heuristomancer (moving it to the services will just be a release of heuristomancer and then update the dependencies).

CORE-8626: gzip/bgzip'd VCF support

---

react-components/package-lock.json
react-components/package.json
react-components/src/util/Autocomplete.js
react-components/src/util/AutocompleteStyles.js

I tested this in GWT - the delete key works now!
The options appear above any elements below the Autocomplete instead of pushing those elements down - yay!

Upgrade to react-select v2

---

de-lib/src/main/java/org/iplantc/de/client/models/viewer/InfoType.java
de-lib/src/main/java/org/iplantc/de/client/util/DiskResourceUtil.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/callbacks/GenomeBrowserUtil.java

following up https://github.com/cyverse-de/heuristomancer/pull/5

Add bedgz type support, expecting tbi index files

---

de-lib/src/main/java/org/iplantc/de/apps/client/gin/CommunityTreeStoreProvider.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/communities/GroupComparator.java
de-lib/src/main/java/org/iplantc/de/client/services/AppServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/GroupServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/converters/GroupListCallbackConverter.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/AppUserServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/GroupServiceFacadeImpl.java
de.properties.tmpl

This is just a subset of the commits in my previous PR for UI-337, mostly the service calls and a few things that my later PRs rely on.

UI-337 Community-related service calls

---

de-lib/src/main/java/org/iplantc/de/shared/DEProperties.java

I'm also stealing this commit from the current PR I have open for UI-336 (letting users pick communities when publishing an app). Since we're planning to release the admin interface first, then the DE side of things, I need this merged in before UI-336 gets merged in.

UI-336 Add community attr from de config

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/AdminCommunitiesView.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/ManageCommunitiesView.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/presenter/AdminCommunitiesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/presenter/AdminManageCommunitiesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/service/AdminCommunityServiceFacade.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/service/impl/AdminCommunityServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/views/AdminCommunitiesViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/views/ManageCommunitiesViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/views/dialogs/AppCommunityListEditorDialog.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/views/dialogs/DeleteCommunityConfirmationDialog.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/views/dialogs/EditCommunityDialog.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/views/dialogs/RetagAppsConfirmationDialog.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/views/BelphegorViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/shared/Belphegor.java
de-lib/src/main/java/org/iplantc/de/commons/client/ErrorHandler.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/communities/CommunitiesViewDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/communities/CommunityDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/communities/CommunityDisplayStrings.properties

UI-346 Add retagging dialog and static IDs to communities tab

---

de-lib/src/main/java/org/iplantc/de/commons/client/ErrorHandler.java
de-lib/src/main/java/org/iplantc/de/commons/client/views/ReactUtilComponents.java
react-components/src/__tests__/util.js
react-components/src/util/ErrorHandler.js
react-components/src/util/ids.js
react-components/src/util/messages.js
react-components/src/util/style.js
react-components/src/util/util.js
react-components/stories/index.stories.js
react-components/stories/util/ErrorHandler.stories.js

React-ified Error Handler

---

react-components/config/webpack.config.prod.js
react-components/package-lock.json
react-components/package.json

This PR is an attempt to replace deps such as `webpack` and `babel` with `react-scripts` in our package dependencies.
It will also update our webpack config with latest CRA config settings for `babel`.

Attempt to use `react-scripts` as build dependency.

---

de-lib/src/main/java/org/iplantc/de/apps/client/AppCategoriesView.java
de-lib/src/main/java/org/iplantc/de/apps/client/AppsListView.java
de-lib/src/main/java/org/iplantc/de/apps/client/AppsToolbarView.java
de-lib/src/main/java/org/iplantc/de/apps/client/CommunitiesView.java
de-lib/src/main/java/org/iplantc/de/apps/client/WorkspaceView.java
de-lib/src/main/java/org/iplantc/de/apps/client/events/selection/CommunitySelectionChangedEvent.java
de-lib/src/main/java/org/iplantc/de/apps/client/gin/AppsGinModule.java
de-lib/src/main/java/org/iplantc/de/apps/client/gin/factory/AppsViewFactory.java
de-lib/src/main/java/org/iplantc/de/apps/client/gin/factory/CommunitiesViewFactory.java
de-lib/src/main/java/org/iplantc/de/apps/client/models/CommunityStringValueProvider.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/AppsViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/WorkspacePresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/categories/AppCategoriesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/communities/CommunitiesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/list/AppsListPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/AppsViewImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/WorkspaceViewImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/communities/CommunitiesViewImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/communities/CommunitiesViewImpl.ui.xml
de-lib/src/main/java/org/iplantc/de/apps/client/views/list/AppsGridViewImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/list/AppsTileViewImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/toolBar/AppsViewToolbarImpl.java
de-lib/src/main/java/org/iplantc/de/apps/shared/AppsModule.java
de-lib/src/main/java/org/iplantc/de/client/models/collaborators/Subject.java
de-lib/src/main/java/org/iplantc/de/client/services/converters/GroupListCallbackConverter.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/Applications.gwt.xml
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/communities/CommunitiesViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/apps/client/presenter/AppsViewPresenterImplTest.java

This is a branch on top of #365, so there are only actually [4 new commits](https://github.com/cyverse-de/ui/pull/366/files/24148141b0d34520703bd3b23071515c0eca201d..3c9d2bd87f323d4a34e66816d2cac28101955a06) here.  
Additionally, the first 3 commits of those 4 are from my first pass at adding Communities in a separate tab which was approved (#341).  So hopefully [this](https://github.com/cyverse-de/ui/pull/366/commits/3c9d2bd87f323d4a34e66816d2cac28101955a06) is the only commit that needs to be reviewed.

Add community listing to Apps window

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/communities/presenter/AdminCommunitiesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/client/services/GroupServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/GroupServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/communities/client/presenter/ManageCommunitiesPresenterImpl.java
react-components/src/communities/styles.js
react-components/src/communities/view/CommunityListing.js
react-components/src/communities/view/ManageCommunitiesView.js
react-components/src/util/table/EmptyTable.js

* Updated the service calls to add a community
* Added a scrollbar to the community listing
* Other little styling changes

Community fixes

---

react-components/src/lib.js

Works in storybook and in the DE

Override mui button textTransform setting

---

react-components/src/analysis/view/AnalysesView.js
react-components/src/analysis/view/dialogs/AnalysisParametersDialog.js
react-components/src/data/search/queryBuilder/DeleteBtn.js
react-components/src/desktop/view/Notifications.js
react-components/src/lib.js
react-components/src/metadata/MetadataTemplateView.js
react-components/src/metadata/admin/EditAttributeFormList.js
react-components/src/metadata/admin/EditMetadataTemplate.js
react-components/src/metadata/admin/OrderedGridToolbar.js
react-components/src/metadata/admin/StringListEditor.js
react-components/src/metadata/style.js

See https://material-ui.com/style/typography/#migration-to-typography-v2
P.S: I may have missed few spots. If so, please update them in your next PR. 🙏

Fix annoying typography variant deprecated warning.

---

de-lib/src/main/java/org/iplantc/de/apps/client/CommunitiesView.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/AppsViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/communities/CommunitiesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/communities/client/ManageCommunitiesView.java
de-lib/src/main/java/org/iplantc/de/communities/client/presenter/ManageCommunitiesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/pipelines/client/views/AppSelectionDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/communities/CommunitiesDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/communities/CommunitiesDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/communities/ManageCommunitiesViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/apps/client/presenter/AppsViewPresenterImplTest.java
react-components/src/communities/styles.js
react-components/src/communities/view/EditCommunity.js
react-components/src/communities/view/EditCommunityDialog.js

This will:
* In the Apps window, deselect communities after the user has submitted a search
* In the Communities window, fix issues regarding searching for apps to add to a community

Communities hotfix

---

de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/InitializationCallbacks.java
de-webapp/src/main/java/org/iplantc/de/server/controllers/BootstrapErrorController.java
de-webapp/src/main/webapp/WEB-INF/jsp/bootstrapError.jsp
react-components/src/__tests__/util.js
react-components/src/util/ErrorExpansionPanel.js
react-components/src/util/messages.js
react-components/src/util/style.js
react-components/src/util/util.js
react-components/stories/index.stories.js
react-components/stories/util/ErrorExpansionPanel.stories.js

With beautification help from Mariah ✨ 
**Before**
**After**
**After, expanded**

CORE-123 and 124 - Update DE's error page with log out btn and error details

---

de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/AnalysesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/client/services/AnalysisServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/AnalysisServiceFacadeImpl.java
react-components/src/analysis/ids.js
react-components/src/analysis/messages.js
react-components/src/analysis/style.js
react-components/src/analysis/view/AnalysesView.js
react-components/src/analysis/view/dialogs/AnalysisInfoDialog.js
react-components/stories/analysis/view/dialogs/AnalysisInfoDialog.stories.js

core-49 add analysis history to analysis info dialog.

---

de-lib/src/main/java/org/iplantc/de/client/services/impl/GroupServiceFacadeImpl.java

This is what the schema in terrain is expecting now

CORE-242 Only provide name and desc in group updates

---

de-lib/src/main/java/org/iplantc/de/client/services/impl/CollaboratorsServiceFacadeImpl.java

This was causing schema validation errors to pop up

CORE-17 Bypass user-info call on empty list during sharing

---

react-components/src/apps/details/AppInfoDialog.js
react-components/src/apps/details/ToolDetails.js
react-components/src/apps/ids.js
react-components/src/apps/quickLaunch/QuickLaunchListing.js
react-components/src/metadata/EditMetadata.js
react-components/src/util/dialog/DEDialogHeader.js
react-components/src/util/dialog/ids.js

These should help me patch up some failing GUI tests

Add static IDs to app info and metadata dialogs

---

react-components/config/env.js
react-components/config/webpack.config.prod.js
react-components/package-lock.json
react-components/package.json
react-components/scripts/build.js
react-components/src/analysis/style.js
react-components/src/analysis/view/AnalysesView.js
react-components/src/apps/admin/AppStats.js
react-components/src/apps/details/AppDetails.js
react-components/src/apps/style.js
react-components/src/communities/styles.js
react-components/src/communities/view/CommunityListing.js
react-components/src/communities/view/EditCommunity.js
react-components/src/data/details/BasicDetails.js
react-components/src/data/details/InfoTypeSelectionList.js
react-components/src/data/details/Tag.js
react-components/src/data/details/TagPanel.js
react-components/src/data/style.js
react-components/src/desktop/view/DesktopView.js
react-components/src/desktop/view/Help.js
react-components/src/desktop/view/Notifications.js
react-components/src/desktop/view/TaskButton.js
react-components/src/desktop/view/UserMenu.js
react-components/src/metadata/EditMetadata.js
react-components/src/metadata/style.js
react-components/src/notifications/style.js
react-components/src/notifications/view/NotificationView.js
react-components/src/notifications/view/dialogs/JoinTeamRequestDialog.js
react-components/src/util/SearchField.js
react-components/src/util/hyperlink/DEHyperLink.js

- Use Loading Mask from `de-components` instead of default `CircularProgress`.
- Remove `jss` styles.
- Remove  `jss` deps.
Note: This branch is on top of #411. So only last 2 commits needs to reviewed.

Loading Mask

---

react-components/src/analysis/view/AnalysesView.js

Reset selection when a filter is applied.

core-287 Fix analyses selection bug.

---

react-components/package-lock.json
react-components/src/apps/admin/AppStats.js

- Fix date parameter being sent the service.

Core 289 Fix Belphegor App Stats

---

react-components/src/analysis/messages.js
react-components/stories/analysis/view/dialogs/ShareWithSupportDialog.stories.js

I also added Storybook knobs so you can change which text in the ShareWithSupportDialog you see.

CORE-330 Update Failed analysis help text to mention stderr file

---

react-components/src/analysis/messages.js
react-components/src/analysis/style.js
react-components/src/analysis/view/dialogs/AnalysisInfoDialog.js

CORE-337 Enable users to copy an analysis ID

---

de-lib/src/main/java/org/iplantc/de/admin/apps/client/ReactAppsAdmin.java
de-lib/src/main/java/org/iplantc/de/admin/apps/client/presenter/grid/AdminAppsGridPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/admin/apps/client/views/editor/AppEditor.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/services/impl/AppAdminServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/client/models/apps/App.java
de-lib/src/main/java/org/iplantc/de/client/models/apps/AppExtra.java
de-lib/src/main/java/org/iplantc/de/client/models/apps/HTCondorRequirements.java
de-lib/src/test/java/org/iplantc/de/admin/apps/client/presenter/grid/AdminAppsListPresenterImplTest.java
react-components/src/apps/admin/AdminAppDetails.js
react-components/src/apps/ids.js
react-components/src/apps/messages.js
react-components/stories/apps/admin/AdminAppDetails.stories.js

CORE-327 Add htcondor extra requirements to Belphegor

---

de-lib/src/main/java/org/iplantc/de/analysis/client/views/dialogs/AnalysisSharingDialog.java
de-lib/src/main/java/org/iplantc/de/analysis/shared/AnalysisModule.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/sharing/dialog/AppSharingDialog.java
de-lib/src/main/java/org/iplantc/de/apps/shared/AppsModule.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/NavigationView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/DiskResourcePresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/navigation/NavigationViewImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/sharing/dialogs/DataSharingDialog.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/dialogs/ToolSharingDialog.java
de-lib/src/main/java/org/iplantc/de/tools/shared/ToolsModule.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/DiskResourcePresenterImplTest.java
react-components/src/notifications/ids.js
react-components/src/notifications/view/NotificationToolbar.js

Mostly just adds some static IDs that were requested by QA, and also fixes a selection bug in the Data window while searching

CORE-116, CORE-150, CORE-239

---

README.md
react-components/README.md

Now that we'll have more devs working on UI, figured it'd be good to get this all documented.  I'm sure I forgot things, but here's a start.

Add docs on react dev and standards

---

react-components/src/analysis/view/AnalysesView.js
react-components/src/analysis/view/dialogs/AnalysisInfoDialog.js
react-components/src/analysis/view/dialogs/AnalysisParametersDialog.js
react-components/src/apps/admin/AppStats.js
react-components/src/apps/listing/AppGridListing.js
react-components/src/collaborators/CollaboratorListing.js
react-components/src/communities/view/CommunityListing.js
react-components/src/metadata/MetadataList.js
react-components/src/metadata/admin/AttributeEnumEditGrid.js
react-components/src/metadata/admin/StringListEditor.js
react-components/src/notifications/view/NotificationView.js
react-components/src/notifications/view/dialogs/RequestHistoryDialog.js
react-components/src/teams/Teams.js
react-components/src/tools/ContainerDevices.js
react-components/src/tools/ContainerPorts.js
react-components/src/tools/ContainerVolumes.js
react-components/src/tools/ContainerVolumesFrom.js
react-components/src/tools/ToolImplementation.js

I updated some imports too since I was modifying the files anyway

Convert all tables to use DETableRow and DECheckbox

---

react-components/package.json
react-components/src/apps/appSearchRegex.js
react-components/src/apps/details/AppDetails.js
react-components/src/apps/details/AppInfoDialog.js
react-components/src/apps/listing/AppGridListing.js
react-components/src/apps/listing/AppTileListing.js

passing to Highlighter.
- Updated few prop-types that were throwing validation errors in dev console.

Add logic to convert search string to regex before 

---

de-lib/src/main/java/org/iplantc/de/apps/integration/client/view/dialogs/ToolListingDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/tools/ToolListingViewDefaultAppearance.java
react-components/src/tools/ids.js
react-components/src/tools/messages.js
react-components/src/tools/requests/NewToolRequestForm.js

* Updated the size of the Tool Listing dialog when selecting a tool in App Editor
* Added static IDs to the New Tool Request form
* Also removed the colons from the text labels in the New Tool Request form

CORE-636 and CORE-626

---

de-lib/src/main/java/org/iplantc/de/shared/DEProperties.java
de-lib/src/main/java/org/iplantc/de/tools/client/views/manage/EditToolViewImpl.java

This PR will add admin config settings for max tool resource requests, and update the `EditTool` view to use these max admin settings when building tool container resource limit drop-down lists in the admin view.

CORE-879 Add admin config settings for max tool resource requests.

---

de-lib/src/main/java/org/iplantc/de/apps/shared/AppsModule.java
de-lib/src/main/java/org/iplantc/de/apps/widgets/client/presenter/AppLaunchPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/widgets/client/view/AppLaunchView.java
de-lib/src/main/java/org/iplantc/de/apps/widgets/client/view/dialogs/ViceLimitDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/widgets/AppLaunchViewDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/widgets/AppLaunchViewDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/widgets/AppLaunchViewDisplayStrings.properties

Wording can definitely be modified for clarity.

CORE-975 Add concurrency limit dialog for interactive jobs
