cyverse-de/ui

de-lib/src/test/java/org/iplantc/de/client/services/impl/DataSearchQueryBuilderTest.java
iplant/modules.gradle

I wasn't quite able to figure out how to revive `testBuildQuery()` since that doesn't assert equality, but containment. But, this is still a big improvement, and brings back most of the functionality, so I'm putting it up.

Revive most DataSearchQueryBuilder tests with JSONAssert

---

de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopWindowManager.java

If a user saves their session while viewing the DE with a big monitor, then logs back in while using a smaller monitor, their windows will be too big to access any of the window buttons (close, minimize, etc.).
Now their saved windows will be resized (if needed) to fit the desktop view so they can have access to the entire window.

CORE-3701 Resize oversize window from saved session

---

de-lib/src/main/java/org/iplantc/de/apps/client/views/list/cells/AppRatingCell.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppRatingCell.css
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppRatingCellDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppsTile.css

Currently, it's possible to attempt to rate an app in Apps Under Development which results in the user getting an error that they cannot rate private apps.  It is not possible to rate external apps, but it does visually look like you could rate an external app (it has the little white glove cursor when hovering).
This PR makes it so that hovering over the private apps and external apps rating cells has the regular black pointer cursor to convey that they are not clickable.  This also adds a tooltip to the private app rating cell that lets the user know that rating private apps is not supported.

CORE-4364 Disable rating private apps

---

de-lib/src/main/java/org/iplantc/de/diskResource/client/DataLinkView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/events/selection/DeleteDataLinkSelected.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/dataLink/DataLinkPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/dataLink/DataLinkViewImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/dataLink/cells/DataLinkPanelCell.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/dataLink/DataLinkPresenterImplTest.java

When a user goes to Create a Public Link to a file, in the Manage Data Links dialog that opens, the Copy Link button will remain enabled when no link is selected (in particular, after a link has been deleted).  Clicking on the Copy Link button then opens the Copy Link dialog with no URL.
This PR does some minor refactoring and then disables the Copy Link button after a link has been deleted.

CORE-4012 Disable Copy Link button after link deleted

---

de-lib/src/main/java/org/iplantc/de/client/models/viewer/FileViewerAutoBeanFactory.java
de-lib/src/main/java/org/iplantc/de/client/models/viewer/Manifest.java
de-lib/src/main/java/org/iplantc/de/client/services/FileEditorServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/FileEditorServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/presenter/FileViewerPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/presenter/MimeTypeViewerResolverFactory.java
de-lib/src/test/java/org/iplantc/de/fileViewers/client/presenter/FileViewerPresenterImplTest.java

When a user opened up a tabular file, saving changes in one file viewer did not cause the other file viewer to update.  The user had to manually refresh the file by hitting the Refresh button for that viewer.  This PR adds logic for cycling through the list of file viewers and updates all other views with the latest changes after a file is saved.
I also refactored out some JSON object manipulations and got the tests for FileViewerPresenterImpl started (though they're not finished, but can be finished later).

CORE-5888 Refresh file viewers after save + refactor + tests

---

de-lib/src/main/java/org/iplantc/de/diskResource/client/NavigationView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/grid/GridViewPresenterImpl.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/grid/GridViewPresenterImplTest.java

In the Data window, if you try to de-favorite a file/folder while viewing the Favorites folder, the view does not refresh and the file/folder remains in the Favorites folder (visually) until you refresh.
I also added some tests since we didn't have anything for GridViewPresenterImpl.

CORE-6530 Remove file from favorites when de-favoriting in Favorites folder

---

de-lib/src/main/java/org/iplantc/de/admin/apps/client/views/grid/AdminAppsColumnModel.java
de-lib/src/main/java/org/iplantc/de/admin/apps/client/views/grid/AdminAppsGridImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/TemplatesListingViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/OntologiesView.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/model/HierarchyTree.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/presenter/OntologiesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/OntologiesViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/OntologiesViewImpl.ui.xml
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/views/PermanentIdRequestViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/refGenome/view/RefGenomeViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/refGenome/view/cells/ReferenceGenomeNameCell.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/systemMessage/view/SystemMessageViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/systemMessage/view/cells/SystemMessageNameCell.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolAdmin/view/ToolAdminViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolAdmin/view/cells/ToolAdminNameCell.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/toolRequest/view/ToolRequestViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/views/BelphegorView.ui.xml
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/views/BelphegorViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/workshopAdmin/view/WorkshopAdminViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/shared/Belphegor.java
de-lib/src/main/java/org/iplantc/de/client/util/StaticIdHelper.java
de-lib/src/main/java/org/iplantc/de/commons/client/widgets/DETree.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/refGenome/ReferenceGenomeNameCellDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/systemMessage/cells/SystemMessageNameCellDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/toolAdmin/cells/ToolAdminViewCellDefaultAppearance.java

This PR is to add more static IDs to Belphegor as requested by QA.
* Each tab in Belphegor should have its own ID (switched to `DETabPanel` class instead of Sencha's `TabPanel` which allows for the tabs to have IDs)
* The App Catalog tab didn't have any IDs so those were added
* I created `DETree` abstract class which allows any child class to specify a `generateDebugID` method for debug IDs on the tree nodes
* The column headers in grids all got static IDs (with use from StaticIDHelper class)
* I also patched up a random NPE that happens if you have saved sessions enabled, save a session with no windows open, and then log in.

CORE-8163 Add more static IDs to Belphegor

---

de-webapp/src/main/java/org/iplantc/de/server/controllers/DeController.java

I'm also changing it to use `url.getFile()` because that includes the query string. But the main part is ignoring it when the path is `/`, so we don't produce a redirect loop.

CORE-8362 quick-fix: ignore the referer's path when it's /, to avoid redirect loop

---

de-lib/src/main/java/org/iplantc/de/client/models/UserSettings.java
de-lib/src/main/java/org/iplantc/de/desktop/Desktop.gwt.xml
de-lib/src/main/java/org/iplantc/de/desktop/client/DesktopView.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/RuntimeCallbacks.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/DesktopViewImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/widgets/PreferencesDialog.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/widgets/PreferencesView.ui.xml
de-lib/src/main/java/org/iplantc/de/desktop/shared/DeModule.java
de-lib/src/main/java/org/iplantc/de/preferences/Preferences.gwt.xml
de-lib/src/main/java/org/iplantc/de/preferences/client/PreferencesView.java
de-lib/src/main/java/org/iplantc/de/preferences/client/events/PrefDlgRetryUserSessionClicked.java
de-lib/src/main/java/org/iplantc/de/preferences/client/gin/PreferencesGinModule.java
de-lib/src/main/java/org/iplantc/de/preferences/client/presenter/PreferencesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/preferences/client/view/PreferencesView.ui.xml
de-lib/src/main/java/org/iplantc/de/preferences/client/view/PreferencesViewImpl.java
de-lib/src/main/java/org/iplantc/de/preferences/shared/Preferences.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/Desktop.gwt.xml
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/DesktopErrorMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/DesktopMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/DesktopMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/PreferencesViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/preferences/client/presenter/PreferencesPresenterImplTest.java
de-webapp/src/main/java/org/iplantc/de/client/gin/DEInjector.java

This PR adds to the UI's resiliency (and mostly fixes a bug) where the UI will still try to save a user's session even when the /secured/sessions callback has failed.
The user will be presented with a message indicating that their saved session could not be loaded and that their current session is not being saved.  When users open the Preferences dialog, they'll have a message indicating that their session couldn't be saved and there's a button to retry hitting the /secured/sessions endpoint.
(most of the changes here are a refactor of Preferences to have a dialog + view + presenter instead of just a dialog)

CORE-8400 Disable saved sessions when /secured/sessions fails and add "Try Again" btn to preferences

---

de-lib/src/main/java/org/iplantc/de/client/models/UserSettings.java
de-lib/src/main/java/org/iplantc/de/desktop/client/DesktopView.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/InitializationCallbacks.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/DesktopErrorMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/DesktopErrorMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/presenter/DesktopPresenterDefaultAppearance.java

This PR enables the UI to be more resilient when /secured/preferences is down.  Previously, the UI would not load if this callback failed.  Now, a default set of preferences will be used, the user will be informed, and the UI will continue loading.

CORE-8365 Use default values when /secured/preferences is down

---

de-lib/src/main/java/org/iplantc/de/apps/client/AppCategoriesView.java
de-lib/src/main/java/org/iplantc/de/apps/client/AppsToolbarView.java
de-lib/src/main/java/org/iplantc/de/apps/client/AppsView.java
de-lib/src/main/java/org/iplantc/de/apps/client/OntologyHierarchiesView.java
de-lib/src/main/java/org/iplantc/de/apps/client/events/SelectedHierarchyNotFound.java
de-lib/src/main/java/org/iplantc/de/apps/client/events/selection/RefreshAppsSelectedEvent.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/AppsViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/callbacks/ParentFilteredHierarchyCallback.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/categories/AppCategoriesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/hierarchies/OntologyHierarchiesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/toolBar/AppsToolbarPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/AppsViewImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/hierarchies/OntologyHierarchiesViewImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/toolBar/AppsViewToolbar.ui.xml
de-lib/src/main/java/org/iplantc/de/apps/client/views/toolBar/AppsViewToolbarImpl.java
de-lib/src/main/java/org/iplantc/de/apps/shared/AppsModule.java
de-lib/src/main/java/org/iplantc/de/commons/client/widgets/DETabPanel.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/toolbar/AppsToolbarViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/apps/client/presenter/AppsViewPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/apps/client/presenter/categories/AppCategoriesPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/apps/client/presenter/hierarchies/OntologyHierarchiesPresenterImplTest.java

Since all the other DE windows have Refresh buttons, the Apps window should probably have a Refresh button as well.
This enables the user to be able to refresh the categories, hierarchies, search results, and app listing at any time, and the user should be brought back to whatever category/hierarchy or search they had before hitting Refresh.
Given the nature of ontologies and how they can change at any time by the admins, there's also logic added to cover the scenario where the user has hit Refresh and the hierarchy they were viewing no longer exists. This can happen if the user has had the apps window open for a long time, the admin has published a new ontology that no longer has the hierarchy they were viewing, and then the user hits Refresh. In this case, the user will be brought back …

CORE-8148 Add Refresh button to Apps Window

---

de-lib/src/main/java/com/sencha/gxt/widget/core/client/grid/LiveGridCheckBoxSelectionModel.java
de-lib/src/main/java/org/iplantc/de/client/util/DiskResourceUtil.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/grid/GridViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/details/DetailsViewImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/dialogs/FileFolderSelectDialog.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/dialogs/FileSelectDialog.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/dialogs/FolderSelectDialog.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/grid/GridViewDnDHandler.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/grid/GridViewImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/toolbar/DiskResourceViewToolbar.ui.xml
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/toolbar/DiskResourceViewToolbarImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/widgets/FileSelectorField.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/widgets/FolderSelectorField.java
de-lib/src/main/java/org/iplantc/de/diskResource/share/DiskResourceModule.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/views/PathListViewer.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/views/toolbar/DiskResourceViewToolbar_onDiskResourceSelectionChangedTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/views/toolbar/DiskResourceViewToolbar_onFolderSelectedTest.java

Additionally
- Modify how "red" file / folder behave in center panel.
- Remove unused menu item.
- Add tests for "red" file / folder selection.

Core 6529 drag-n-drop not clearing previous selection if you try to select a "red" file/folder

---

de-lib/src/main/java/org/iplantc/de/client/DEClientConstants.java
de-lib/src/main/java/org/iplantc/de/client/DEClientConstants.properties
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/InitializationCallbacks.java
de-lib/src/test/java/org/iplantc/de/desktop/client/presenter/DesktopNotifications_PresenterTest.java
de-lib/src/test/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImplTest.java
de-webapp/src/main/java/org/iplantc/de/conf/DeWebSecurityConfig.java
de-webapp/src/main/java/org/iplantc/de/server/controllers/BootstrapErrorController.java
de-webapp/src/main/webapp/WEB-INF/jsp/bootstrapError.jsp

This PR is for getting the user out of a neverending loading spinner in the DE when the UI fails to retrieve the properties file or if one of the bootstrap services is down.  The user will be presented with an error page that gives them the option to email support and/or find other avenues for staying up-to-date on CyVerse status.

CORE-8364 Add an error page for when the properties or bootstrap services fail

---

de-lib/src/main/java/org/iplantc/de/desktop/client/DesktopView.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/InitializationCallbacks.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/DesktopViewImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/widgets/UnseenNotificationsView.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/widgets/UnseenNotificationsView.ui.xml
de-lib/src/main/java/org/iplantc/de/notifications/shared/Notifications.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/views/BaseUnseenNotificationsAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/views/UnseenNotificationsStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/views/UnseenNotificationsStrings.properties

This PR gives users the chance to retry fetching their recent notifications for viewing in the notification dropdown if the /secured/notifications callback fails during login.  Currently, if this callback fails, there's no other chance in the UI to get the list of recent notifications (though users could still attempt to view them via the Notification window).

CORE-8366 Add retry btn to notification dropdown on /secured/notifications failure

---

de-lib/src/main/java/org/iplantc/de/client/models/UserInfo.java
de-lib/src/main/java/org/iplantc/de/client/models/UserSettings.java
de-lib/src/main/java/org/iplantc/de/shared/DEProperties.java

If the UI is unable to get a user's preferences, a default set of user preferences is used.  One of those default settings is using the user's home directory, retrieved from the bootstrap endpoint, as the default output folder for analyses.  If the data-info service is down while the UI is calling bootstrap, the path to the user's home directory stored in `UserInfo` will be empty.  
This PR attempts to use the irods home path from the configs plus the user's username to construct their home directory path as a default value in the case that data-info is down.  If this effort fails, then no default output folder is set.  The user will have to pick some directory they have write access to at app launch or change their preferences.

CORE-8420 Construct user home dir from configs if data-info is down

---

de-lib/src/main/java/org/iplantc/de/apps/client/AppsListView.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/categories/AppCategoriesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/list/AppsListPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/list/AppsListViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/apps/client/presenter/categories/AppCategoriesPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/apps/client/presenter/list/AppsListPresenterImplTest.java

If HPC apps fail to load, the Apps grid will mistakenly appear as if HPC apps did load because apps are listed.  These apps are actually the same apps listed from whatever previous category/hierarchy the user had selected.  Now, if HPC is down, the grid will clear and the grid's heading will inform the user of the app load error.
Also, discovered that when the user hits Refresh, duplicate handlers were getting added to the view - this is now fixed.

CORE-8434 Clear Apps grid when HPC app load fails

---

de-lib/src/main/java/org/iplantc/de/client/models/UserSettings.java
de-lib/src/main/java/org/iplantc/de/desktop/client/DesktopView.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/RuntimeCallbacks.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/SaveSessionPeriodic.java
de-lib/src/main/java/org/iplantc/de/preferences/client/presenter/PreferencesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/preferences/client/view/PreferencesViewImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/DesktopErrorMessages.properties

This PR should fix:
- Saved Session checkbox getting unchecked when the saved sessions service comes back up
- When the saved sessions service comes back up, the Try Again button and error message in the Preferences window are removed
- If saved sessions goes down while the user is logged in, the periodic session save will continue to attempt to save their session for a certain number of retries (currently 8 retries is 2 minutes) before disabling itself and letting the user know their session was not saved

CORE-8400 Improvements to saved sessions resiliency

---

de-lib/src/main/java/org/iplantc/de/apps/client/AppCategoriesView.java
de-lib/src/main/java/org/iplantc/de/apps/client/AppsView.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/AppsViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/categories/AppCategoriesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/client/gin/ServicesInjector.java
de-lib/src/main/java/org/iplantc/de/client/gin/ServicesModule.java
de-lib/src/main/java/org/iplantc/de/client/models/CommonModelAutoBeanFactory.java
de-lib/src/main/java/org/iplantc/de/client/models/RootLevelMap.java
de-lib/src/main/java/org/iplantc/de/client/models/UserInfo.java
de-lib/src/main/java/org/iplantc/de/client/models/UserSettings.java
de-lib/src/main/java/org/iplantc/de/client/models/bootstrap/Preferences.java
de-lib/src/main/java/org/iplantc/de/client/models/bootstrap/Session.java
de-lib/src/main/java/org/iplantc/de/client/models/diskResources/RootFolders.java
de-lib/src/main/java/org/iplantc/de/client/services/OauthServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/OauthServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/gin/DEGinModule.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/InitializationCallbacks.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/windows/DEAppsWindow.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/navigation/proxy/FolderRpcProxyImpl.java
de-lib/src/main/java/org/iplantc/de/preferences/client/PreferencesView.java
de-lib/src/main/java/org/iplantc/de/preferences/client/presenter/PreferencesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/categories/AppCategoriesViewDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/DesktopMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/DesktopMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/PreferencesViewDefaultAppearance.java

* If the `user_info` key is missing the username, name, or email information, the user will now be redirected to the DE's error page so they can try logging in again.
* If the `session` key contains an error, the loginTime will not be populated (which is acceptable) and the UI will recheck for any redirects from the oauth service when the Apps window is opened (for example, the Agave redirect).
* If the `workspace` key contains an error, the UI will by default assume the user is a new user and show the prompt for the introduction/tutorial upon login.  The workspace ID isn't used in the UI, so that is ignored.
* If the `data_info` key contains an error, default home and trash paths will be used.  If the user opens the Data window and gets a successful callback from `/filesystem/root` the …

CORE-8443 Improve UI's handling of individual bootstrap service errors

---

de-lib/src/main/java/org/iplantc/de/desktop/client/views/widgets/ServiceDownPanel.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/widgets/ServiceDownPanel.ui.xml
de-lib/src/main/java/org/iplantc/de/desktop/client/views/windows/IplantWindowBase.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/window/ServiceDownPanelDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/window/ServiceDownPanelDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/window/ServiceDownPanelDisplayStrings.properties

This PR is just to update the wording and appearance of the panel that gets swapped into the Apps/Data/Analysis window when the UI discovers that the backend services those windows require are down.

Update ServiceDownPanel appearance

---

de-lib/src/main/java/org/iplantc/de/client/models/viewer/InfoType.java
de-lib/src/main/java/org/iplantc/de/client/util/DiskResourceUtil.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/callbacks/EnsemblUtil.java

I didn't add bigBed support to stuff having to do with structured text viewers, because bigBed is a binary/indexed version of BED rather than the tabular format normal BED is.
Won't be that helpful without https://github.com/cyverse-de/heuristomancer/pull/1 (though I guess it'll allow manually setting it at least).

CORE-8535: Add bigBed support (mostly) where BED is supported

---

de-lib/src/main/java/org/iplantc/de/apps/integration/client/view/AppsEditorView.java
de-lib/src/main/java/org/iplantc/de/apps/widgets/client/events/AppTemplateFetched.java
de-lib/src/main/java/org/iplantc/de/apps/widgets/client/presenter/AppLaunchPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/widgets/client/view/AppLaunchView.java
de-lib/src/main/java/org/iplantc/de/client/util/AppTemplateUtils.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/windows/AppLaunchWindow.java
de-lib/src/main/java/org/iplantc/de/shared/AppLaunchCallback.java
de-lib/src/main/java/org/iplantc/de/shared/AppsCallback.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/widgets/AppLaunchViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/apps/widgets/client/presenter/AppLaunchPresenterImplTest.java

This turned out to be a bit of a refactor since we were making service calls directly from `AppLaunchWindow` that I moved to `AppLaunchPresenterImpl`.  Otherwise, the goal of this PR was to refactor any calls related to the App Launch window to use `AppLaunchCallback` instead of `AppsCallback` since it is possible for users to be able to launch apps even if the metadata service is down.  (Currently the metadata service being down is capable of causing most `AppsCallbacks` to fail which would disable the Apps, App Editor, and Workflow builder windows.)

CORE-8490 UI Resiliency - App Launch Window

---

de-lib/src/main/java/org/iplantc/de/desktop/client/DesktopView.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/views/DesktopViewImpl.java

It works!
I have the feeling I'm supposed to be using the presenter here (no other views seem to import ErrorHandler, particularly, but the presenter which corresponds to this does seem to use it via a provider), but I would need advising on how to move this stuff around. This does successfully reduce the size of the initial download, while increasing the leftovers fragment a little bit and creating one extra split (at least in my testing, it bundled the PreferencesDialog with the preexisting AppLaunchWindow split, but DEFeedbackDialog got its own).

Migrate PreferencesDialog and DEFeedbackDialog to using AsyncProviderWrapper

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/EditMetadataTemplateViewImpl.java

If you edit a Metadata Template attribute in Belphegor, then try to drag and drop that attribute to a different location, your changes are lost.
This change immediately commits changes to the liststore so changes are preserved.

CORE-7014 Fix Metadata Template bug during DND

---

de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppStatusCellDefaultAppearance.java

I accidentally removed this code to fix a bug in Belphegor where this was causing NPE, not realizing this also affected the DE.  Now there's a null check so Belphegor can do its thing and the DE will show the lock.

CORE-8597 Fix issue where private apps do not show lock icon

---

de-lib/src/main/java/org/iplantc/de/apps/client/presenter/hierarchies/OntologyHierarchiesPresenterImpl.java

CORE-8441 - Private apps were listing the Unclassified hierarchies in the App Details view, which incorrectly conveyed that those apps were public.
CORE-8599 - Hitting the Refresh button in the Apps window causes the go() method to be rerun.  The unclassifiedHierarchies list was never reset in the go() method which would cause dupes to get added every time the Refresh button was pressed.  This led to an incorrect number of Unclassified hierarchies listed in the App Details view.

CORE-8599 and CORE-8441

---

de-lib/src/main/java/org/iplantc/de/diskResource/client/DataLinkView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/GridView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/dataLink/DataLinkViewImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/dataLink/DataLinkViewImpl.ui.xml
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/sharing/dialogs/ShareResourceLinkDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/dataLink/DataLinkMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/dataLink/DataLinkMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/dataLink/DataLinkViewDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/GridViewDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/GridViewDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/presenter/GridViewPresenterDefaultAppearance.java

When creating public data links, users thought the verbiage and buttons were trying to convey that opening the data link window automatically copied the data link into the user's clipboard.  This is changing the wording so that it's clearer that users still have to manually copy the link.
From "Copy Link" to "Show Link"
From "Copy" title to "Public Data Link" title.  Cancel button has been removed so as to not indicate there is an action to cancel.

CORE-4232 Rename Copy Link button in Data Link window for clarity

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/presenter/MetadataTemplatesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/presenter/PermanentIdRequestPresenter.java

this was just me experimenting to see if using async providers for the service facades was a plausible thing to do, but it actually works, so may as well put it in -- the split ends up about 2kb, which is all of the DiskResourceServiceFacade that's actually used anywhere in Belphegor (metadata templates stuff and permanent ID request stuff both use it, but only a tiny bit).

Put the DiskResourceServiceFacade behind a code split in belphegor

---

de-lib/src/main/java/org/iplantc/de/apps/widgets/client/presenter/AppLaunchPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/client/models/apps/integration/AppTemplate.java
de-lib/src/test/java/org/iplantc/de/apps/widgets/client/presenter/AppLaunchPresenterImplTest.java

This PR fixes a bug where the UI was not checking the Retain Inputs flag (debug key) during analysis relaunch.

CORE-7539 When relaunching an analysis, the Retain Inputs flag does not persist

---

de-lib/src/main/java/org/iplantc/de/client/models/HasSplittableError.java
de-lib/src/main/java/org/iplantc/de/client/models/UserInfo.java
de-lib/src/main/java/org/iplantc/de/client/models/bootstrap/AppsInfo.java
de-lib/src/main/java/org/iplantc/de/client/models/bootstrap/DataInfo.java
de-lib/src/main/java/org/iplantc/de/client/models/bootstrap/Preferences.java
de-lib/src/main/java/org/iplantc/de/client/models/bootstrap/Session.java
de-lib/src/main/java/org/iplantc/de/client/models/bootstrap/SystemIds.java
de-lib/src/main/java/org/iplantc/de/client/models/bootstrap/UserBootstrap.java
de-lib/src/main/java/org/iplantc/de/client/models/bootstrap/Workspace.java

We discovered recently that if there are any kind of errors during bootstrap (for example, if the backend has updated the bootstrap JSON), the UI will use default values as expected, but will hide the cause of the use of defaults.
This change will log the bootstrap errors that occur within the UI prior to using defaults for more transparency.

CORE-8613 Log errors from the UI during bootstrap

---

de-lib/src/main/java/org/iplantc/de/commons/client/ErrorHandler.java
de-lib/src/main/java/org/iplantc/de/commons/client/info/ErrorAnnouncementConfig.java
de-lib/src/main/java/org/iplantc/de/commons/client/info/IplantAnnouncementConfig.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/GridView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/ToolbarView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/DiskResourcePresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/grid/GridViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/toolbar/DiskResourceViewToolbarImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/GridViewDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/GridViewDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/grid/presenter/GridViewPresenterDefaultAppearance.java

When a user tried to save a metadata file with a name that already existed, the user was only informed that they should try again with no details as to why. Now if the file already exists, the user will be better informed, for any other errors they'll get the standard error handler message.  I also thought it would be better to unmask the Save dialog instead of hiding it so users don't have to type the file names in again.
I also added more key strings to the ErrorHandler class to parse for in the error JSON from what I've seen Agave use and examples in other tickets.

CORE-8709 Better error message handling when a user tries to save metadata

---

de-lib/src/main/java/org/iplantc/de/client/models/notifications/NotificationCategory.java
de-lib/src/main/java/org/iplantc/de/client/models/notifications/payload/PayloadTool.java
de-lib/src/main/java/org/iplantc/de/client/models/notifications/payload/PayloadToolMsg.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/util/NotificationUtil.java

I was thinking we don't currently have anything to show the user if they click on the notification, but if there are ideas for that, do let me know.  I'm thinking once the UI changes are implemented, this would open up the new [Tools window](https://docs.google.com/document/d/1SEnFQtBirQVoLAaStq1oF3KroK7i6i6YR21grx2qCSE/edit?usp=sharing).

CORE-8723 Enable notifications for tool sharing messages

---

de-lib/src/main/java/org/iplantc/de/client/models/collaborators/Collaborator.java
de-lib/src/main/java/org/iplantc/de/client/models/groups/GroupAutoBeanFactory.java
de-lib/src/main/java/org/iplantc/de/client/models/groups/UpdateMemberRequest.java
de-lib/src/main/java/org/iplantc/de/client/models/groups/UpdateMemberResult.java
de-lib/src/main/java/org/iplantc/de/client/models/groups/UpdateMemberResultList.java
de-lib/src/main/java/org/iplantc/de/client/services/GroupServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/GroupServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/GroupDetailsView.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/GroupView.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/ManageCollaboratorsView.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/events/AddGroupMemberSelected.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/events/AddGroupSelected.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/events/GroupSaved.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/presenter/GroupDetailsPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenter.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/GroupDetailsViewImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/GroupViewImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/ManageCollaboratorsViewImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/dialogs/GroupDetailsDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/GroupDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/GroupDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/collaborators/GroupViewDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/collaborators/client/presenter/GroupDetailsPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenterTest.java

NOTE: This is rebased on top of CORE-8794 PR #121.  You only need to view the commits starting from `CORE-8792 Add endpoint for adding group members`
I had to add the concept of a mode to the GroupDetailsView for this to work - basically if you're creating a brand new Collaborator List, you're in the `ADD` mode which makes sure that the list and any members you add aren't saved until you complete the form - first the list gets saved, then the members get added.  If you're editing a list, you're in the `EDIT` mode and members get immediately added as you select them.

CORE-8792 Allow users to add members to a Collaborator List

---

de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppsTile.gss

Blake asked for this change this morning. The light gray border against a white background didn’t stand out enough.  Switching to black.
Before:
After:

CORE-8833 Make app tile view selection more visible

---

de-lib/src/main/java/org/iplantc/de/apps/integration/client/presenter/AppsEditorPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/integration/client/view/AppsEditorView.java
de-lib/src/main/java/org/iplantc/de/client/models/tool/Tool.java
de-lib/src/main/java/org/iplantc/de/resources/client/uiapps/integration/AppIntegrationErrorMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/integration/AppsEditorViewDefaultAppearance.java
de-lib/src/main/resources/org/iplantc/de/resources/client/messages/IplantErrorStrings.properties

If the user opens (or copies) an app for editing, and that app uses a tool that has been marked as `deprecated`, then the following warning message will display in a dialog pop-up:
> This app uses a deprecated tool. You can still edit and use this private app, but you will have to choose a newer version of the tool before it can be made public.
This message will not display when a user opens a public app to edit its labels.

CORE-8845 Add deprecated tool warning when editing private apps.

---

de-lib/src/main/java/org/iplantc/de/client/models/pipelines/PipelineTask.java
de-lib/src/main/java/org/iplantc/de/client/models/pipelines/ServicePipelineTask.java
de-lib/src/main/java/org/iplantc/de/client/models/tool/ToolImage.java
de-lib/src/main/java/org/iplantc/de/pipelines/client/presenter/PipelineViewPresenter.java
de-lib/src/main/java/org/iplantc/de/pipelines/client/util/PipelineAutoBeanUtil.java
de-lib/src/main/java/org/iplantc/de/resources/client/uiapps/integration/AppIntegrationErrorMessages.java
de-lib/src/main/resources/org/iplantc/de/resources/client/messages/IplantErrorStrings.properties

This PR will update the `PipelineViewPresenter` to check for deprecated tools, using the details added by cyverse-de/apps#61, in order to display a warning when opening a workflow for editing that uses apps with `deprecated` tools, or when adding apps that use `deprecated` tools to a workflow.

CORE-8858 Add deprecated tool warnings to workflow editor.

---

de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/InitializationCallbacks.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/DesktopMessages.properties

I also changed some wording.  If preferences failed to load during bootstrap, we retry fetching preferences when opening the Preferences window.  In the case of a new user, "restored" doesn't make much sense, but "loaded" should work for all scenarios.

CORE-8883 Prevent new users from seeing an error banner regarding preferences

---

de-lib/src/main/java/org/iplantc/de/client/models/collaborators/Subject.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/util/CollaboratorsUtil.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/commons/views/sharing/SharingPermissionNameCellDefaultAppearance.java

When the UI looks up sharing info, it first gets a list of usernames that have permissions on the resource.  Once that's returned, then a secondary call is made to look up the user information to be able to display the user's name.  In the case of the anonymous user, the secondary call returns no information because that user doesn't exist in grouper, so the UI creates a "dummy" collaborator to display.  The UI has been updated to create a dummy collaborator where the username is both the id and the name.  The username is then what is displayed in the UI for that particular case.

Patch up NPEs and fix dummy subject creation for anonymous user

---

de-lib/src/main/java/org/iplantc/de/client/services/DiskResourceServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/DiskResourceServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/client/util/DiskResourceUtil.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterWindowEventHandler.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/events/RequestSendToEnsemblEvent.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/DiskResourcePresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/toolbar/DiskResourceViewToolbarImpl.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/callbacks/EnsemblUtil.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/callbacks/ShareAnonymousCallback.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/views/ExternalVisualizationURLViewerImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/fileViewers/FileViewerContextualHelpStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/fileViewers/FileViewerStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/fileViewers/callbacks/ShareAnonymousCallbackDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/views/toolbar/DiskResourceViewToolbar_onDiskResourceSelectionChangedTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/views/toolbar/DiskResourceViewToolbar_onFolderSelectedTest.java

The "View in Genome Browser" menu item is now enabled when multiple genome files or their index files are selected. At least 1 genome file must be selected, but if an index file isn't selected, its existence is still checked and it's still automatically shared with the anon user. The file viewer will only open if only 1 genome file is selected.
The "View in Genome Browser" dialog will now display the URLs for all selected genome files (but not their index files), and its help text and labels have been updated.

CORE-8893 Enable "View in Genome Browser" for multiple genome files.

---

de-lib/src/main/java/org/iplantc/de/apps/client/presenter/toolBar/AppsToolbarPresenterImpl.java
de-lib/src/test/java/org/iplantc/de/apps/client/presenter/toolBar/AppsToolbarPresenterImplTest.java

This was already doing it one place, I just fixed it the other place. The other convenience is this let me copy the tests from the other place, but that's still the thing I'd like the most review on!
(I wanted a bit of a break from thinking about ops/thinking in Go, and code splits are something perpetually available to work on, hence this PR, heh)

Make the NewToolRequestDialog use an AsyncProviderWrapper

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/EditMetadataTemplateViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/gin/OntologiesGinModule.java
de-lib/src/main/java/org/iplantc/de/apps/client/gin/AppsGinModule.java
de-lib/src/main/java/org/iplantc/de/client/models/diskResources/MetadataTemplateAttributeType.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/OntologyAutoBeanFactory.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/OntologyClass.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/OntologyHierarchy.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/OntologyLookupServiceDoc.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/OntologyLookupServiceResponse.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/OntologyLookupServiceResults.java
de-lib/src/main/java/org/iplantc/de/client/services/OntologyLookupServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/OntologyLookupServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/MetadataView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/MetadataPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/proxy/OntologyLookupServiceLoadConfig.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/proxy/OntologyLookupServiceProxy.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/MetadataTemplateView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/search/MetadataTermSearchField.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/DiskResource.gwt.xml
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/search/MetadataTermSearchFieldDefaultAppearance.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/search/OntologySearchResult.html
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/metadata/MetadataPresenterImplTest.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/metadata/proxy/OntologyLookupServiceProxyTest.java
de.properties.tmpl

This PR will add a `MetadataTermSearchField` widget that can create a ComboBox for use as a Metadata Template attribute type.
The ComboBox can lookup terms using the Ontology Lookup Service ["select" endpoint](http://www.ebi.ac.uk/ols/docs/api#_select_terms) to populate its drop-down list. This ComboBox will allow the user to either select one of the suggested terms, or enter any other text they wish as the metadata attribute's value.
The `MetadataTermSearchField` can also be used as a `Converter` for the ComboBox widget in a GridRowEditing column, such as in the AVU editing grid.
The OLS searches are restricted to only `class` entity types by default. The search results are presented in the ComboBox drop-down with the ontology class `label` listed first in bold, and underneath the …

CORE-8980 Add Ontology Lookup Service autocomplete widget to DE Metadata Template forms

---

de-lib/src/main/java/org/iplantc/de/client/models/sharing/Sharing.java

The `equals` logic was slightly incorrect because it was only checking if the user and the permission value were the same between two `Sharing` objects.  However, in the case we just discovered where a user may want to change the permissions for multiple files at a time for one user, it is necessary to check the user, the permission value, and also that the resource is the same between the two objects being compared.

DE-1164 Fix logic for comparing Sharing equality

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/EditMetadataTemplateViewImpl.java
de-lib/src/main/java/org/iplantc/de/client/models/diskResources/MetadataTemplateAttributeType.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/AstroThesaurusDoc.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/AstroThesaurusDocLabel.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/AstroThesaurusResponse.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/AstroThesaurusResult.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/MetadataTermSearchResult.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/OntologyAutoBeanFactory.java
de-lib/src/main/java/org/iplantc/de/client/models/ontologies/OntologyLookupServiceDoc.java
de-lib/src/main/java/org/iplantc/de/client/services/OntologyLookupServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/OntologyLookupServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/commons/client/widgets/SearchField.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/MetadataPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/proxy/AstroThesaurusLoadConfig.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/proxy/AstroThesaurusProxy.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/proxy/MetadataTermLoadConfig.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/proxy/MetadataTermSearchProxy.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/proxy/OntologyLookupServiceLoadConfig.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/metadata/proxy/OntologyLookupServiceProxy.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/MetadataTemplateView.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/search/MetadataTermSearchField.java
de-lib/src/main/java/org/iplantc/de/server/auth/BaseUrlConnector.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/search/MetadataTermSearchFieldDefaultAppearance.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/metadata/MetadataPresenterImplTest.java
de.properties.tmpl

This PR will add [Unified Astronomy Thesaurus](https://vocabs.ands.org.au/the-unified-astronomy-thesaurus) ontology term autocomplete support to DE and Belphegor Metadata Template forms.
This Metadata Template attribute field looks and works similar to the "Ontology Lookup Service" attribute field added by cyverse-de/ui#192, except the UAT search service offers much more limited search parameters, so there are no query param settings available for UAT term attributes in Belphegor.
This PR may be easier to review by each individual commit.

CORE-9000 + CORE-9001: Add 'Unified Astronomy Thesaurus' ontology term autocomplete support to DE and Belphegor Metadata Template forms

---

build.gradle
iplant/webapps.gradle

As I said in chat, I tested this with Paul's React POC PR and everything seemed to work just fine.  SDM is working.  Prod builds seem to be working.
I did see an issue filed in the gradle plugin [repo](https://github.com/jiakuan/gwt-gradle-plugin) about the *nocache.js file not being generated, but I see it getting loaded into the browser when I do a production build so I don't think it's an issue for us.

Switch to new gradle plugin that supports JsInterop

---

de-lib/src/main/java/org/iplantc/de/client/models/errors/diskResources/DiskResourceErrorAutoBeanFactory.java
de-lib/src/main/java/org/iplantc/de/client/models/errors/diskResources/ErrorGetStat.java
de-lib/src/main/java/org/iplantc/de/client/models/errors/diskResources/categories/ErrorGetManifestCategory.java
de-lib/src/main/java/org/iplantc/de/client/models/errors/diskResources/categories/ErrorGetStatCategory.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterWindowEventHandler.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/views/dialogs/FileSelectDialog.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/callbacks/EnsemblUtil.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/callbacks/GenomeBrowserUtil.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/gin/FileViewerGinModule.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/presenter/FileViewerPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/presenter/MimeTypeViewerResolverFactory.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/views/ExternalVisualizationURLViewerImpl.java
de-lib/src/main/java/org/iplantc/de/resources/client/messages/IplantDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/shared/AsyncProviderWrapper.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/fileViewers/FileViewerErrorStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/fileViewers/FileViewers.gwt.xml
de-lib/src/main/java/org/iplantc/de/theme/base/client/fileViewers/callbacks/GenomeBrowserUtilDefaultAppearance.java
de-lib/src/main/resources/org/iplantc/de/resources/client/messages/IplantDisplayStrings.properties

- Also renamed `EnsemblUtil` to `GenomeBrowserUtil` because Ensembl is a genome browser by itself and this class is a generic util.

De 1166 Allow users to manually select index file(s) for genome browsers.

---

de-lib/src/main/java/org/iplantc/de/collaborators/client/util/UserSearchRPCProxy.java

There's no real harm in the user seeing the `default` collaborator list, it's just that they also can't really do anything with it.  If they click on it, they get an error message about being unable to add `default` to their collaborators (which makes sense since they're trying to add `default` to `default` without knowing it).

CORE-9038 Prevent user from seeing default collab list in search results

---

de-lib/src/main/java/org/iplantc/de/teams/client/presenter/TeamSearchRpcProxy.java
de-lib/src/main/java/org/iplantc/de/teams/client/presenter/TeamsPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/teams/client/views/TeamsViewImpl.java
de-lib/src/test/java/org/iplantc/de/teams/client/presenter/TeamSearchRpcProxyTest.java

I also added in a change so that if you clear out the search text, the "All Teams" filter will be applied.
Then I also realized the team creator names were missing when searching, so I added that.

CORE-9041 Clear out the teams grid if no search results are returned for clarity

---

de-lib/src/main/java/org/iplantc/de/analysis/client/views/AnalysesToolBarImpl.java
de-lib/src/main/java/org/iplantc/de/analysis/client/views/widget/AnalysisDotMenu.java

This PR will enable the Analyses window's cancel menu items for batch jobs that have any submitted or running child jobs, even if the parent job is already marked as completed.

CORE-9014 Enable cancel action for uncompleted batch jobs.

---

de-lib/src/main/java/org/iplantc/de/desktop/client/views/windows/FileViewerWindow.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/FileViewer.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/callbacks/FileSaveCallback.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/presenter/FileViewerPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/fileViewers/client/views/SaveAsDialogOkSelectHandler.java
de-lib/src/test/java/org/iplantc/de/fileViewers/client/presenter/FileViewerPresenterImplTest.java

This is just when the user attempts to close the file with unsaved changes.  If the save is successful, the viewer will close.

CORE-5143 Close FileViewer after prompt to save

---

de-lib/src/main/java/org/iplantc/de/apps/widgets/client/view/editors/LaunchAnalysisView.ui.xml
de-lib/src/main/java/org/iplantc/de/apps/widgets/client/view/editors/LaunchAnalysisViewImpl.java

Sencha's Checkbox appearance contains "white-space: nowrap;" with no clear way to change that.  This causes the Retain Inputs text to stretch beyond the window's width.
I didn't immediately see any other elements that didn't adjust with the width of the window, but just in case, I added horizontal scroll support.

CORE-4809 Add horizontal scroll to AppLaunch and switch to GWT Checkbox

---

de-lib/src/main/java/org/iplantc/de/preferences/client/view/PreferencesView.ui.xml
de-lib/src/main/java/org/iplantc/de/preferences/client/view/PreferencesViewImpl.java

QA Preferences tests are failing because the Default Output Folder items aren't able to fit in the field set they're in.  I updated that section from having a fixed height to using a CssFloatLayoutContainer so the field set will expand to fit the size of the children.  Also added a scroll bar in case all of the preferences extend beyond the size of the Preferences dialog.

CORE-9107 Fix Preferences sizing issue

---

de-lib/src/main/java/org/iplantc/de/commons/client/info/IplantAnnouncementConfig.java

Note: I didn't think any styling changes were necessary. After increasing the time to 10s I was able to read the message without issues.

core-9155 increase announcer time to 10s

---

de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/util/NotificationWebSocketManager.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/util/SystemMessageWebSocketManager.java
de-webapp/src/main/java/org/iplantc/de/server/websocket/MessageHandler.java
de-webapp/src/main/java/org/iplantc/de/server/websocket/ReceiveNotificationsDirect.java
de-webapp/src/main/java/org/iplantc/de/server/websocket/amqp/AMQPConnectionManager.java

** Merge only after the 2.19 Release **
If the UI can't connect to AMQP, the `Connection` returned from the `ConnectionFactory` in `AMQPConnectionManager.java` is null. The changes are mostly just making sure we keep doing null checks and trying to get new connections from `ConnectionFactory`.  If despite that, we still end up with a null `Channel` in `MessageHandler.java`, the websocket gets closed.  
From there, [this logic](https://github.com/cyverse-de/ui/blob/master/de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java#L221-L224) tries to reopen the websocket and then restarts the cycle in `AMQPConnectionManager`.

CORE-9157 Enable UI to try to reconnect to AMQP after a failure to connect

---

de-lib/src/main/java/org/iplantc/de/apps/widgets/client/view/editors/arguments/ReferenceAnnotationEditor.java
de-lib/src/main/java/org/iplantc/de/apps/widgets/client/view/editors/arguments/ReferenceGenomeEditor.java
de-lib/src/main/java/org/iplantc/de/apps/widgets/client/view/editors/arguments/ReferenceSequenceEditor.java
de-lib/src/main/java/org/iplantc/de/apps/widgets/client/view/editors/arguments/converters/ReferenceGenomeEditorConverter.java

It seems that the editor will fill the combobox with whatever was supplied to it, regardless of what's actually in the ListStore. So for this, I'm forcing the value to be chosen from the store, and in the case where the store is initially empty, I pick a value after the store has been populated.

CORE-9224 Update analysis reference genome dropdown with latest genomes

---

react-components/src/apps/admin/AppStats.js
react-components/src/apps/style.js

This PR will adjust the App Stats table layout so that only the table rows will scroll, and not the toolbar or pagination action footer.
The App Stats table height is now also dynamic, so that it attempts to fill in all available space on window resize.
Also fixed the `ActionsComponent` prop in the `TablePagination` component so the custom pagination icons are used once again (maybe got lost in the MUI v1 upgrade?).

CORE-8430 Adjust App Stats table layout and heights.

---

react-components/src/__tests__/apps.js
react-components/src/__tests__/util.js
react-components/src/data/details/TagPanel.js
react-components/src/util/Autocomplete.js
react-components/stories/index.stories.js
react-components/stories/util/Autocomplete.stories.js
react-components/stories/util/SearchField.stories.js
react-components/stories/util/TriggerField.stories.js

I've had this in my querybuilder branch for a while and figured I should probably go ahead and separate this out into its own PR. 
This is mostly just copied over from TagPanel.  I added the styled options (MenuItems), but couldn't figure out how to style the Input component to material-ui.  If you follow the example from material-ui, it looks right but the input component clears its state and loses focus if you receive new options/suggestions for some reason.

Autocomplete component

---

de-lib/src/main/java/org/iplantc/de/teams/client/presenter/EditTeamPresenterImpl.java

The readOption privilege is fake and must be separated into 2 privileges: read and optIn

CORE-9262 Fix error when creating team with readOptin privilege

---

react-components/src/metadata/MetadataTemplateView.js

This PR will update MetadataTemplateView attribute panels to auto-expand when new fields are added by the user.
Previously, if the attribute's ExpansionPanel was collapsed (as is the case by default if there are no AVUs matching that attribute name), and the user clicked the "Add" icon next to the attribute name, the panel would not expand on its own, and the user might not know to click the expand icon on the right side of the form to display the newly added AVU value field.

Auto-expand MetadataTemplateView attribute panel when adding fields.

---

de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/EditMetadataTemplateViewImpl.java
de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/ReactMetadataAdminViews.java
react-components/package-lock.json
react-components/package.json
react-components/src/metadata/AstroThesaurusSearchField.js
react-components/src/metadata/MetadataTemplateView.js
react-components/src/metadata/OntologyLookupServiceSearchField.js
react-components/src/metadata/admin/AttributeEnumEditGrid.js
react-components/src/metadata/admin/EditAttributeFormList.js
react-components/src/metadata/admin/EditMetadataTemplate.js
react-components/src/metadata/admin/OntologyLookupServiceSettings.js
react-components/src/metadata/admin/StringListEditor.js
react-components/src/util/FormField.js
react-components/stories/metadata/MetadataTemplate.stories.js

This PR will replace `redux-form` fields with `Formik` fields in the admin `EditMetadataTemplate` dialog and in `util/FormField`.
Only the `data/search/QueryBuilder` forms now use `redux-form`, but I think we can convert those in a later PR.

CORE-25 Replace redux-form with Formik in EditMetadataTemplate

---

react-components/src/analysis/view/AnalysesView.js
react-components/src/analysis/view/dialogs/AnalysisInfoDialog.js
react-components/src/analysis/view/dialogs/AnalysisParametersDialog.js
react-components/src/notifications/view/NotificationView.js
react-components/src/notifications/view/dialogs/RequestHistoryDialog.js
react-components/src/util/table/EnhancedTableHead.js

This PR will enhance `EnhancedTableHead` with changes that will be used for CORE-7743, plus some minor refactoring for code readability: 
* Added `id` field to `columnData` props, instead of auto generating based on name/key and the `ids` prop, which also fixed a bug in `RequestHistoryDialog`.
* Added an optional `padding` field to `columnData` props, which can override the overall `padding` prop.
* Check `onRequestSort` prop before setting a column sort handler (fixes NPE in `analysis` stories).

CORE-103 Enhance EnhancedTableHead

---

react-components/src/analysis/view/AnalysesView.js
react-components/src/analysis/view/dialogs/AnalysisInfoDialog.js
react-components/src/analysis/view/dialogs/AnalysisParametersDialog.js
react-components/src/apps/listing/AppGridListing.js
react-components/src/collaborators/CollaboratorListing.js
react-components/src/communities/view/CommunityListing.js
react-components/src/notifications/view/NotificationView.js
react-components/src/notifications/view/dialogs/RequestHistoryDialog.js
react-components/src/util/table/EnhancedTableHead.js

Something about MUI's CSS for `Fab` and `Checkbox` components make them float over our stickied `EnhancedTableHead` when scrolling through tables. Adding the `EnhancedTableHead` to a `Table` after a `TableBody` prevents this odd behavior.
Also updated `EnhancedTableHead` and `NotificationView` checkbox column padding.

CORE-120 Fix EnhancedTableHead rendering with FAB and Checkboxes.

---

de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/RuntimeCallbacks.java

Basically:
1. If there's a DATA parameter, only the Data window will open regardless of saved session (this is the original functionality for "data only" viewer that I'm maintaining)
1. The user's session is fetched
1. Any other parameters are then parsed (apps, error, state)

Make sure query parameter windows are on top

---

de-lib/src/main/java/org/iplantc/de/apps/client/AppsView.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/AppsViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/communities/client/ManageCommunitiesView.java
de-lib/src/main/java/org/iplantc/de/communities/client/presenter/ManageCommunitiesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/pipelines/client/views/AppSelectionDialog.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/communities/CommunitiesDisplayStrings.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/communities/CommunitiesDisplayStrings.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/communities/ManageCommunitiesViewDefaultAppearance.java
react-components/src/communities/messages.js
react-components/src/communities/view/EditCommunity.js

The `Add` button becomes disabled and there's a tooltip indicating that Agave apps cannot be added to communities at this time.

Disable adding agave apps to communities

---

react-components/src/metadata/MetadataTemplateView.js
react-components/src/util/FormField.js
react-components/stories/metadata/MetadataTemplate.stories.js

This PR will add a `FormCheckboxStringValue` component that saves and parses existing metadata
values as a "true" or "false" string, since metadata AVU values must be strings, and the service will throw the validation error `ERR_ILLEGAL_ARGUMENT` for non-string values set in the AVU's `value` field.
We have existing metadata AVUs with "true" or "false" values for some template attributes with `Boolean` types, since the previous GXT component saved these attribute values as "true" or "false".
Also included a fix for read-only checkboxes in templates.

CORE-234 Fixes for Metadata Template checkboxes

---

react-components/src/data/edit/Comment.js
react-components/src/data/edit/DotMenu.js
react-components/src/data/edit/EditComments.js
react-components/src/data/edit/EditCommentsMenuItems.js
react-components/src/data/edit/style.js
react-components/stories/data/edit/EditComments.stories.js
react-components/stories/index.stories.js

This is the edit comments dialog written in react. This pull request only contains the UI portion of this element. Currently the "Retract" and "+" buttons do nothing, but in the future will make API requests to retract or add a comment respectively. The comments can be sorted by recency (dates will all have the same format once api is implemented) and by owner, these sorts can be seen after clicking the dot menu.
The comment section itself is in a Dialog Content element and is therefore scrollable, there is a max width so longer comments will wrap.

Edit comments dialog

---

de-lib/src/main/java/org/iplantc/de/commons/client/ErrorHandler.java

The logic I wrote assumed the messages would be strings, but they're sometimes json objects.  Should fix issues like this:

Enable any JSON obj to show in ErrorHandler messages

---

react-components/src/apps/quickLaunch/QuickLaunchListing.js

This PR will move the `ActionsPopper` components out of the `ListQuickLaunches` Grid list and replace them with a single `ActionsPopper`.
Otherwise an `ActionsPopper` will be created for every Quick Launch item in the list, and they will all show at the same time when a public `qLaunch` is clicked, with the popover for the last `qLaunch` in the list always on top.
This caused the `useQuickLaunch` button to always open the last `qLaunch` in that list.
Also refactored the `ActionsPopper` debug IDs so they are associated with
the buttons that also have the `onClick` handlers.

CORE-308 Fix for using public Quick Launches.

---

de-lib/src/main/java/org/iplantc/de/client/services/impl/DiskResourceServiceFacadeImpl.java

This PR will remove the `includefiles` param from `/filesystem/directory` endpoint calls.
The `data-info` directory endpoint's `includefiles` param is obsolete, so it will no longer be supported in terrain's API after cyverse-de/terrain#127 (it's already ignored anyway).

CORE-9 Remove includefiles param from directory endpoint calls.

---

de-lib/src/main/java/org/iplantc/de/commons/client/CommonUiConstants.java
de-lib/src/main/java/org/iplantc/de/commons/client/CommonUiConstants.properties
de-lib/src/main/java/org/iplantc/de/desktop/client/DesktopView.java
de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
de-webapp/src/main/webapp/WEB-INF/jsp/de.jsp
react-components/src/desktop/ids.js
react-components/src/desktop/messages.js
react-components/src/desktop/style.js
react-components/src/desktop/view/DesktopView.js
react-components/src/desktop/view/Help.js
react-components/src/desktop/view/Notifications.js
react-components/src/desktop/view/UserMenu.js
react-components/stories/desktop/view/DesktopView.stories.js

* Moved About, Introduction, and User Manual under Help icon
* Changed Forum link to a link to the learning center
* Added links to email support and also to open the Intercom chat window under the Help icon
* Added tooltips to the desktop menu items and to the support menu items
* Updated the styling for the desktop menu items

Updates to Desktop menus

---

react-components/src/desktop/messages.js
react-components/src/desktop/view/UserMenu.js

Here's an example:
Very much open to suggestions on how to make the tooltip wordings more clear

CORE-326 Add icons and tooltips to the desktop User menu items

---

Dockerfile

NCSU uses Internet2's InCommon certificate authority. Adding it as a trusted certificate authority shouldn't pose much of a risk, and will make it easier for us to deploy to sites that use it.

added the Internet2 InCommon intermediate CA certificate

---

react-components/src/analysis/view/AnalysesMenuItems.js

Since deleting a job does not cancel it, this prevents users from accidentally deleting running jobs.

CORE-128 Disable Delete option for running jobs

---

react-components/package-lock.json
react-components/package.json
react-components/src/tools/ManageTools.js

Selected in blue, hover in gray:
I'm now leaning towards not adding the checkboxes back because we also use this view in the App Editor to select a tool for the app.  Having the checkboxes in that case might be confusing, as if you can create a workflow of tools.  We could add a flag to toggle having the checkboxes, but, as Sriram said, probably it's unlikely users are trying to select/deal with multiple tools in the Manage Tools window anyway.

Update ManageTools table to use DETableRow

---

de-lib/src/main/java/org/iplantc/de/apps/widgets/client/view/editors/AppStepResourcesViewImpl.java
de-lib/src/main/java/org/iplantc/de/client/models/tool/ToolResourceLimits.java

This PR will update the `AppStepResourcesView` editor to init the resource requirement fields with any defaults set in the resource limits model.
Currently only the relaunch endpoint includes default settings, added by cyverse-de/apps#196.

CORE-633 Update AppStepResourcesView editor with resource defaults.

---

de-lib/src/main/java/org/iplantc/de/apps/client/AppsListView.java
de-lib/src/main/java/org/iplantc/de/apps/client/AppsView.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/AppsViewPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/presenter/list/AppsListPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/list/AppListViewImpl.java
de-lib/src/main/java/org/iplantc/de/apps/client/views/list/ReactAppListing.java
de-lib/src/main/java/org/iplantc/de/client/models/collaborators/Subject.java
de-lib/src/main/java/org/iplantc/de/client/services/converters/SubjectListCallbackConverter.java
de-lib/src/main/java/org/iplantc/de/communities/client/presenter/ManageCommunitiesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/pipelines/client/presenter/PipelineViewPresenter.java
react-components/src/apps/listing/AppListingView.js

This will:
* Disable communities showing up in search results for sharing.
* Enable opening the apps window with single selection or multi selection.  Single selection will fix the bug where it looks like you can add multiple apps to communities or workflows at a time. This will then also fix the bug in communities where you had to deselect the previously selected app in order to add a new app to a community.

Community fixes

---

de-lib/src/main/java/org/iplantc/de/analysis/client/AnalysesView.java
de-lib/src/main/java/org/iplantc/de/analysis/client/presenter/AnalysesPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/client/services/AnalysisServiceFacade.java
de-lib/src/main/java/org/iplantc/de/client/services/impl/AnalysisServiceFacadeImpl.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/AnalysesMessages.java
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/AnalysesMessages.properties
de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/presenter/AnalysesPresenterDefaultAppearance.java
react-components/src/analysis/messages.js
react-components/src/analysis/view/AnalysesMenuItems.js
react-components/src/analysis/view/AnalysesView.js
react-components/stories/analysis/view/AnalysesView.stories.js

This PR will add mutli-select relaunch support to the AnalysesView, allowing users to select more than 1 analysis to relaunch with the new analyses auto-relaunch endpoint (cyverse-de/apps#197).
This PR will also add range-selection support to the AnalysesView.

CORE-877 Add mutli-select relaunch support to AnalysesView

---

react-components/src/metadata/MetadataTemplateView.js

The metadata presenter strips number/integer values from AVUs when converting to Autobeans in prep for submission to metadata endpoints.
This fix will convert number values to strings in the metadata form's `handleSubmit` function before passing the metadata to the presenter.

CORE-763 Fix AVU number values in Metadata Template forms.

---

react-components/src/metadata/MetadataTemplateView.js
react-components/src/metadata/messages.js

The Metadata Template "Save" button is no longer disabled when the form has validation errors.
Instead an alert dialog displays informing the user there are errors.
Also removed FAB buttons in favor of Icon buttons.

CORE-414 Improve behavior of "Save" button in Metadata Template forms

---

react-components/src/desktop/NewUserTourSteps.js

Fix wording in intro's Help section

---

de-lib/src/main/java/org/iplantc/de/collaborators/client/presenter/CollaborationPresenterImpl.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/presenter/ManageCollaboratorsPresenter.java
de-lib/src/main/java/org/iplantc/de/collaborators/client/views/dialogs/GroupDetailsDialog.java

* Fix NPE when attempting to add a collaborator for sharing via the "Choose Collaborators" option in the sharing dialog
* Fix Collaborators List dialog hiding automatically after clicking OK to save a Collaborator List.  The user was getting no feedback on whether the List didn't save or whether it was still in the process of saving.

Fix NPE and loading mask issues with Collaborators window/dialog

---

react-components/src/analysis/view/AnalysesView.js
react-components/src/analysis/view/DotMenu.js
react-components/src/analysis/view/dialogs/ShareWithSupportDialog.js
react-components/stories/analysis/view/AnalysesView.stories.js

* Updating `statusClick` to use `index` instead of an `analysis` object was missed in #478.
* The `handleRowClick` logic also should have been updated in #478 to set the selected items to only the row clicked.
* The `DotMenu` was also updated to select that row when clicked, so that the single-item actions are available in that menu.
* The `AnalysesView` story `presenter` was updated to also log analysis info in console logs for various methods.

CORE-968 Fix Analysis View statusClick and handleRowClick.

---

de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/BulkMetadataViewImpl.java

Since the file selector includes the entire resource path, having this validation would always fail on the `/` character being present in the path (e.g. /iplant/home/username).  Considering users can only pick items from the data store and cannot manually type in a file/folder, validating the resource name is unnecessary at this stage anyway.

Remove DiskResourceNameValidator from BulkMetadataViewImpl

---

de-lib/src/main/java/org/iplantc/de/client/models/diskResources/Folder.java
de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/grid/proxy/FolderContentsRpcProxyImpl.java
de-lib/src/test/java/org/iplantc/de/diskResource/client/presenters/grid/proxy/FolderContentsRpcProxyTest.java

Pretty straightforward, hopefully, if it's me putting up an old-ui PR :laughing:
Just trying to make it so the UI doesn't use that field at all, so that it won't care if it's there or not.

Remove totalBad field from all usage, since it isn't really being used anyway
